// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Design implementation internals
// See Vhello_uvm.h for the primary calling header

#include "Vhello_uvm__pch.h"

VL_ATTR_COLD void Vhello_uvm_uvm_pkg___eval_static__TOP__uvm_pkg(Vhello_uvm_uvm_pkg* vlSelf, VlProcessRef vlProcess);
VL_ATTR_COLD void Vhello_uvm_uvm_pkg__03a__03auvm_object__Vclpkg___eval_static__TOP__uvm_pkg__03a__03auvm_object__Vclpkg(Vhello_uvm_uvm_pkg__03a__03auvm_object__Vclpkg* vlSelf);
VL_ATTR_COLD void Vhello_uvm_uvm_pkg__03a__03auvm_resource_options__Vclpkg___eval_static__TOP__uvm_pkg__03a__03auvm_resource_options__Vclpkg(Vhello_uvm_uvm_pkg__03a__03auvm_resource_options__Vclpkg* vlSelf);
VL_ATTR_COLD void Vhello_uvm_uvm_pkg__03a__03auvm_resource_pool__Vclpkg___eval_static__TOP__uvm_pkg__03a__03auvm_resource_pool__Vclpkg(Vhello_uvm_uvm_pkg__03a__03auvm_resource_pool__Vclpkg* vlSelf);
VL_ATTR_COLD void Vhello_uvm_uvm_pkg__03a__03auvm_resource__Tz1__Vclpkg___eval_static__TOP__uvm_pkg__03a__03auvm_resource__Tz1__Vclpkg(Vhello_uvm_uvm_pkg__03a__03auvm_resource__Tz1__Vclpkg* vlSelf, VlProcessRef vlProcess);
VL_ATTR_COLD void Vhello_uvm_uvm_pkg__03a__03auvm_resource__Tz4__Vclpkg___eval_static__TOP__uvm_pkg__03a__03auvm_resource__Tz4__Vclpkg(Vhello_uvm_uvm_pkg__03a__03auvm_resource__Tz4__Vclpkg* vlSelf, VlProcessRef vlProcess);
VL_ATTR_COLD void Vhello_uvm_uvm_pkg__03a__03auvm_resource__Tz5__Vclpkg___eval_static__TOP__uvm_pkg__03a__03auvm_resource__Tz5__Vclpkg(Vhello_uvm_uvm_pkg__03a__03auvm_resource__Tz5__Vclpkg* vlSelf, VlProcessRef vlProcess);
VL_ATTR_COLD void Vhello_uvm_uvm_pkg__03a__03auvm_resource__Tz6__Vclpkg___eval_static__TOP__uvm_pkg__03a__03auvm_resource__Tz6__Vclpkg(Vhello_uvm_uvm_pkg__03a__03auvm_resource__Tz6__Vclpkg* vlSelf, VlProcessRef vlProcess);
VL_ATTR_COLD void Vhello_uvm_uvm_pkg__03a__03auvm_object_registry__pi1__Vclpkg___eval_static__TOP__uvm_pkg__03a__03auvm_object_registry__pi1__Vclpkg(Vhello_uvm_uvm_pkg__03a__03auvm_object_registry__pi1__Vclpkg* vlSelf, VlProcessRef vlProcess);
VL_ATTR_COLD void Vhello_uvm_uvm_pkg__03a__03auvm_object_registry__pi2__Vclpkg___eval_static__TOP__uvm_pkg__03a__03auvm_object_registry__pi2__Vclpkg(Vhello_uvm_uvm_pkg__03a__03auvm_object_registry__pi2__Vclpkg* vlSelf, VlProcessRef vlProcess);
VL_ATTR_COLD void Vhello_uvm_uvm_pkg__03a__03auvm_object_registry__pi3__Vclpkg___eval_static__TOP__uvm_pkg__03a__03auvm_object_registry__pi3__Vclpkg(Vhello_uvm_uvm_pkg__03a__03auvm_object_registry__pi3__Vclpkg* vlSelf, VlProcessRef vlProcess);
VL_ATTR_COLD void Vhello_uvm_uvm_pkg__03a__03auvm_resource__Tz16__Vclpkg___eval_static__TOP__uvm_pkg__03a__03auvm_resource__Tz16__Vclpkg(Vhello_uvm_uvm_pkg__03a__03auvm_resource__Tz16__Vclpkg* vlSelf, VlProcessRef vlProcess);
VL_ATTR_COLD void Vhello_uvm_uvm_pkg__03a__03auvm_object_registry__pi4__Vclpkg___eval_static__TOP__uvm_pkg__03a__03auvm_object_registry__pi4__Vclpkg(Vhello_uvm_uvm_pkg__03a__03auvm_object_registry__pi4__Vclpkg* vlSelf, VlProcessRef vlProcess);
VL_ATTR_COLD void Vhello_uvm_uvm_pkg__03a__03auvm_component_registry__Tz44__Vclpkg___eval_static__TOP__uvm_pkg__03a__03auvm_component_registry__Tz44__Vclpkg(Vhello_uvm_uvm_pkg__03a__03auvm_component_registry__Tz44__Vclpkg* vlSelf, VlProcessRef vlProcess);
VL_ATTR_COLD void Vhello_uvm_uvm_pkg__03a__03auvm_object_registry__pi7__Vclpkg___eval_static__TOP__uvm_pkg__03a__03auvm_object_registry__pi7__Vclpkg(Vhello_uvm_uvm_pkg__03a__03auvm_object_registry__pi7__Vclpkg* vlSelf, VlProcessRef vlProcess);
VL_ATTR_COLD void Vhello_uvm_uvm_pkg__03a__03auvm_resource__Tz17__Vclpkg___eval_static__TOP__uvm_pkg__03a__03auvm_resource__Tz17__Vclpkg(Vhello_uvm_uvm_pkg__03a__03auvm_resource__Tz17__Vclpkg* vlSelf, VlProcessRef vlProcess);
VL_ATTR_COLD void Vhello_uvm_uvm_pkg__03a__03auvm_object_registry__pi8__Vclpkg___eval_static__TOP__uvm_pkg__03a__03auvm_object_registry__pi8__Vclpkg(Vhello_uvm_uvm_pkg__03a__03auvm_object_registry__pi8__Vclpkg* vlSelf, VlProcessRef vlProcess);
VL_ATTR_COLD void Vhello_uvm_uvm_pkg__03a__03auvm_object_registry__pi9__Vclpkg___eval_static__TOP__uvm_pkg__03a__03auvm_object_registry__pi9__Vclpkg(Vhello_uvm_uvm_pkg__03a__03auvm_object_registry__pi9__Vclpkg* vlSelf, VlProcessRef vlProcess);
VL_ATTR_COLD void Vhello_uvm_uvm_pkg__03a__03auvm_object_registry__pi10__Vclpkg___eval_static__TOP__uvm_pkg__03a__03auvm_object_registry__pi10__Vclpkg(Vhello_uvm_uvm_pkg__03a__03auvm_object_registry__pi10__Vclpkg* vlSelf, VlProcessRef vlProcess);
VL_ATTR_COLD void Vhello_uvm_uvm_pkg__03a__03auvm_resource__Tz53__Vclpkg___eval_static__TOP__uvm_pkg__03a__03auvm_resource__Tz53__Vclpkg(Vhello_uvm_uvm_pkg__03a__03auvm_resource__Tz53__Vclpkg* vlSelf, VlProcessRef vlProcess);
VL_ATTR_COLD void Vhello_uvm_uvm_pkg__03a__03auvm_resource___Vclpkg___eval_static__TOP__uvm_pkg__03a__03auvm_resource___Vclpkg(Vhello_uvm_uvm_pkg__03a__03auvm_resource___Vclpkg* vlSelf, VlProcessRef vlProcess);
VL_ATTR_COLD void Vhello_uvm_uvm_pkg__03a__03auvm_resource__Tz54__Vclpkg___eval_static__TOP__uvm_pkg__03a__03auvm_resource__Tz54__Vclpkg(Vhello_uvm_uvm_pkg__03a__03auvm_resource__Tz54__Vclpkg* vlSelf, VlProcessRef vlProcess);
VL_ATTR_COLD void Vhello_uvm_uvm_pkg__03a__03auvm_resource__Tz55__Vclpkg___eval_static__TOP__uvm_pkg__03a__03auvm_resource__Tz55__Vclpkg(Vhello_uvm_uvm_pkg__03a__03auvm_resource__Tz55__Vclpkg* vlSelf, VlProcessRef vlProcess);
VL_ATTR_COLD void Vhello_uvm_uvm_pkg__03a__03auvm_resource__Tz52__Vclpkg___eval_static__TOP__uvm_pkg__03a__03auvm_resource__Tz52__Vclpkg(Vhello_uvm_uvm_pkg__03a__03auvm_resource__Tz52__Vclpkg* vlSelf, VlProcessRef vlProcess);
VL_ATTR_COLD void Vhello_uvm_uvm_pkg__03a__03auvm_object_registry__pi11__Vclpkg___eval_static__TOP__uvm_pkg__03a__03auvm_object_registry__pi11__Vclpkg(Vhello_uvm_uvm_pkg__03a__03auvm_object_registry__pi11__Vclpkg* vlSelf, VlProcessRef vlProcess);
VL_ATTR_COLD void Vhello_uvm_uvm_pkg__03a__03auvm_object_registry__pi12__Vclpkg___eval_static__TOP__uvm_pkg__03a__03auvm_object_registry__pi12__Vclpkg(Vhello_uvm_uvm_pkg__03a__03auvm_object_registry__pi12__Vclpkg* vlSelf, VlProcessRef vlProcess);
VL_ATTR_COLD void Vhello_uvm_uvm_pkg__03a__03auvm_object_registry__pi13__Vclpkg___eval_static__TOP__uvm_pkg__03a__03auvm_object_registry__pi13__Vclpkg(Vhello_uvm_uvm_pkg__03a__03auvm_object_registry__pi13__Vclpkg* vlSelf, VlProcessRef vlProcess);
VL_ATTR_COLD void Vhello_uvm_uvm_pkg__03a__03auvm_resource__Tz66__Vclpkg___eval_static__TOP__uvm_pkg__03a__03auvm_resource__Tz66__Vclpkg(Vhello_uvm_uvm_pkg__03a__03auvm_resource__Tz66__Vclpkg* vlSelf, VlProcessRef vlProcess);
VL_ATTR_COLD void Vhello_uvm_uvm_pkg__03a__03auvm_object_registry__pi14__Vclpkg___eval_static__TOP__uvm_pkg__03a__03auvm_object_registry__pi14__Vclpkg(Vhello_uvm_uvm_pkg__03a__03auvm_object_registry__pi14__Vclpkg* vlSelf, VlProcessRef vlProcess);
VL_ATTR_COLD void Vhello_uvm_uvm_pkg__03a__03auvm_object_registry__pi15__Vclpkg___eval_static__TOP__uvm_pkg__03a__03auvm_object_registry__pi15__Vclpkg(Vhello_uvm_uvm_pkg__03a__03auvm_object_registry__pi15__Vclpkg* vlSelf, VlProcessRef vlProcess);
VL_ATTR_COLD void Vhello_uvm_uvm_pkg__03a__03auvm_object_registry__pi16__Vclpkg___eval_static__TOP__uvm_pkg__03a__03auvm_object_registry__pi16__Vclpkg(Vhello_uvm_uvm_pkg__03a__03auvm_object_registry__pi16__Vclpkg* vlSelf, VlProcessRef vlProcess);
VL_ATTR_COLD void Vhello_uvm_uvm_pkg__03a__03auvm_object_registry__pi17__Vclpkg___eval_static__TOP__uvm_pkg__03a__03auvm_object_registry__pi17__Vclpkg(Vhello_uvm_uvm_pkg__03a__03auvm_object_registry__pi17__Vclpkg* vlSelf, VlProcessRef vlProcess);
VL_ATTR_COLD void Vhello_uvm_uvm_pkg__03a__03auvm_object_registry__pi18__Vclpkg___eval_static__TOP__uvm_pkg__03a__03auvm_object_registry__pi18__Vclpkg(Vhello_uvm_uvm_pkg__03a__03auvm_object_registry__pi18__Vclpkg* vlSelf, VlProcessRef vlProcess);
VL_ATTR_COLD void Vhello_uvm_uvm_pkg__03a__03auvm_object_registry__pi19__Vclpkg___eval_static__TOP__uvm_pkg__03a__03auvm_object_registry__pi19__Vclpkg(Vhello_uvm_uvm_pkg__03a__03auvm_object_registry__pi19__Vclpkg* vlSelf, VlProcessRef vlProcess);
VL_ATTR_COLD void Vhello_uvm_uvm_pkg__03a__03auvm_object_registry__pi23__Vclpkg___eval_static__TOP__uvm_pkg__03a__03auvm_object_registry__pi23__Vclpkg(Vhello_uvm_uvm_pkg__03a__03auvm_object_registry__pi23__Vclpkg* vlSelf, VlProcessRef vlProcess);
VL_ATTR_COLD void Vhello_uvm_uvm_pkg__03a__03auvm_object_registry__pi24__Vclpkg___eval_static__TOP__uvm_pkg__03a__03auvm_object_registry__pi24__Vclpkg(Vhello_uvm_uvm_pkg__03a__03auvm_object_registry__pi24__Vclpkg* vlSelf, VlProcessRef vlProcess);
VL_ATTR_COLD void Vhello_uvm_uvm_pkg__03a__03auvm_object_registry__pi25__Vclpkg___eval_static__TOP__uvm_pkg__03a__03auvm_object_registry__pi25__Vclpkg(Vhello_uvm_uvm_pkg__03a__03auvm_object_registry__pi25__Vclpkg* vlSelf, VlProcessRef vlProcess);
VL_ATTR_COLD void Vhello_uvm_uvm_pkg__03a__03auvm_object_registry__pi26__Vclpkg___eval_static__TOP__uvm_pkg__03a__03auvm_object_registry__pi26__Vclpkg(Vhello_uvm_uvm_pkg__03a__03auvm_object_registry__pi26__Vclpkg* vlSelf, VlProcessRef vlProcess);
VL_ATTR_COLD void Vhello_uvm_uvm_pkg__03a__03auvm_object_registry__pi27__Vclpkg___eval_static__TOP__uvm_pkg__03a__03auvm_object_registry__pi27__Vclpkg(Vhello_uvm_uvm_pkg__03a__03auvm_object_registry__pi27__Vclpkg* vlSelf, VlProcessRef vlProcess);
VL_ATTR_COLD void Vhello_uvm_uvm_pkg__03a__03auvm_object_registry__pi28__Vclpkg___eval_static__TOP__uvm_pkg__03a__03auvm_object_registry__pi28__Vclpkg(Vhello_uvm_uvm_pkg__03a__03auvm_object_registry__pi28__Vclpkg* vlSelf, VlProcessRef vlProcess);
VL_ATTR_COLD void Vhello_uvm_uvm_pkg__03a__03auvm_object_registry__pi29__Vclpkg___eval_static__TOP__uvm_pkg__03a__03auvm_object_registry__pi29__Vclpkg(Vhello_uvm_uvm_pkg__03a__03auvm_object_registry__pi29__Vclpkg* vlSelf, VlProcessRef vlProcess);
VL_ATTR_COLD void Vhello_uvm_uvm_pkg__03a__03auvm_object_registry__pi30__Vclpkg___eval_static__TOP__uvm_pkg__03a__03auvm_object_registry__pi30__Vclpkg(Vhello_uvm_uvm_pkg__03a__03auvm_object_registry__pi30__Vclpkg* vlSelf, VlProcessRef vlProcess);
VL_ATTR_COLD void Vhello_uvm_uvm_pkg__03a__03auvm_object_registry__pi31__Vclpkg___eval_static__TOP__uvm_pkg__03a__03auvm_object_registry__pi31__Vclpkg(Vhello_uvm_uvm_pkg__03a__03auvm_object_registry__pi31__Vclpkg* vlSelf, VlProcessRef vlProcess);
VL_ATTR_COLD void Vhello_uvm_uvm_pkg__03a__03auvm_object_registry__pi32__Vclpkg___eval_static__TOP__uvm_pkg__03a__03auvm_object_registry__pi32__Vclpkg(Vhello_uvm_uvm_pkg__03a__03auvm_object_registry__pi32__Vclpkg* vlSelf, VlProcessRef vlProcess);
VL_ATTR_COLD void Vhello_uvm_uvm_pkg__03a__03auvm_object_registry__pi33__Vclpkg___eval_static__TOP__uvm_pkg__03a__03auvm_object_registry__pi33__Vclpkg(Vhello_uvm_uvm_pkg__03a__03auvm_object_registry__pi33__Vclpkg* vlSelf, VlProcessRef vlProcess);
VL_ATTR_COLD void Vhello_uvm_uvm_pkg__03a__03auvm_object_registry__pi34__Vclpkg___eval_static__TOP__uvm_pkg__03a__03auvm_object_registry__pi34__Vclpkg(Vhello_uvm_uvm_pkg__03a__03auvm_object_registry__pi34__Vclpkg* vlSelf, VlProcessRef vlProcess);
VL_ATTR_COLD void Vhello_uvm_uvm_pkg__03a__03auvm_object_registry__pi35__Vclpkg___eval_static__TOP__uvm_pkg__03a__03auvm_object_registry__pi35__Vclpkg(Vhello_uvm_uvm_pkg__03a__03auvm_object_registry__pi35__Vclpkg* vlSelf, VlProcessRef vlProcess);
VL_ATTR_COLD void Vhello_uvm_uvm_pkg__03a__03auvm_object_registry__pi36__Vclpkg___eval_static__TOP__uvm_pkg__03a__03auvm_object_registry__pi36__Vclpkg(Vhello_uvm_uvm_pkg__03a__03auvm_object_registry__pi36__Vclpkg* vlSelf, VlProcessRef vlProcess);
VL_ATTR_COLD void Vhello_uvm_uvm_pkg__03a__03auvm_object_registry__pi37__Vclpkg___eval_static__TOP__uvm_pkg__03a__03auvm_object_registry__pi37__Vclpkg(Vhello_uvm_uvm_pkg__03a__03auvm_object_registry__pi37__Vclpkg* vlSelf, VlProcessRef vlProcess);
VL_ATTR_COLD void Vhello_uvm_uvm_pkg__03a__03auvm_object_registry__pi38__Vclpkg___eval_static__TOP__uvm_pkg__03a__03auvm_object_registry__pi38__Vclpkg(Vhello_uvm_uvm_pkg__03a__03auvm_object_registry__pi38__Vclpkg* vlSelf, VlProcessRef vlProcess);
VL_ATTR_COLD void Vhello_uvm_uvm_pkg__03a__03auvm_object_registry__pi39__Vclpkg___eval_static__TOP__uvm_pkg__03a__03auvm_object_registry__pi39__Vclpkg(Vhello_uvm_uvm_pkg__03a__03auvm_object_registry__pi39__Vclpkg* vlSelf, VlProcessRef vlProcess);
VL_ATTR_COLD void Vhello_uvm_uvm_pkg__03a__03auvm_object_registry__pi40__Vclpkg___eval_static__TOP__uvm_pkg__03a__03auvm_object_registry__pi40__Vclpkg(Vhello_uvm_uvm_pkg__03a__03auvm_object_registry__pi40__Vclpkg* vlSelf, VlProcessRef vlProcess);
VL_ATTR_COLD void Vhello_uvm_uvm_pkg__03a__03auvm_object_registry__pi41__Vclpkg___eval_static__TOP__uvm_pkg__03a__03auvm_object_registry__pi41__Vclpkg(Vhello_uvm_uvm_pkg__03a__03auvm_object_registry__pi41__Vclpkg* vlSelf, VlProcessRef vlProcess);
VL_ATTR_COLD void Vhello_uvm_uvm_pkg__03a__03auvm_object_registry__pi42__Vclpkg___eval_static__TOP__uvm_pkg__03a__03auvm_object_registry__pi42__Vclpkg(Vhello_uvm_uvm_pkg__03a__03auvm_object_registry__pi42__Vclpkg* vlSelf, VlProcessRef vlProcess);
VL_ATTR_COLD void Vhello_uvm_uvm_pkg__03a__03auvm_object_registry__pi43__Vclpkg___eval_static__TOP__uvm_pkg__03a__03auvm_object_registry__pi43__Vclpkg(Vhello_uvm_uvm_pkg__03a__03auvm_object_registry__pi43__Vclpkg* vlSelf, VlProcessRef vlProcess);
VL_ATTR_COLD void Vhello_uvm_uvm_pkg__03a__03auvm_object_registry__pi44__Vclpkg___eval_static__TOP__uvm_pkg__03a__03auvm_object_registry__pi44__Vclpkg(Vhello_uvm_uvm_pkg__03a__03auvm_object_registry__pi44__Vclpkg* vlSelf, VlProcessRef vlProcess);
VL_ATTR_COLD void Vhello_uvm_uvm_pkg__03a__03auvm_object_registry__pi45__Vclpkg___eval_static__TOP__uvm_pkg__03a__03auvm_object_registry__pi45__Vclpkg(Vhello_uvm_uvm_pkg__03a__03auvm_object_registry__pi45__Vclpkg* vlSelf, VlProcessRef vlProcess);
VL_ATTR_COLD void Vhello_uvm_uvm_pkg__03a__03auvm_object_registry__pi46__Vclpkg___eval_static__TOP__uvm_pkg__03a__03auvm_object_registry__pi46__Vclpkg(Vhello_uvm_uvm_pkg__03a__03auvm_object_registry__pi46__Vclpkg* vlSelf, VlProcessRef vlProcess);
VL_ATTR_COLD void Vhello_uvm_uvm_pkg__03a__03auvm_object_registry__Tz79__Vclpkg___eval_static__TOP__uvm_pkg__03a__03auvm_object_registry__Tz79__Vclpkg(Vhello_uvm_uvm_pkg__03a__03auvm_object_registry__Tz79__Vclpkg* vlSelf, VlProcessRef vlProcess);
VL_ATTR_COLD void Vhello_uvm_uvm_pkg__03a__03auvm_object_registry__Tz80__Vclpkg___eval_static__TOP__uvm_pkg__03a__03auvm_object_registry__Tz80__Vclpkg(Vhello_uvm_uvm_pkg__03a__03auvm_object_registry__Tz80__Vclpkg* vlSelf, VlProcessRef vlProcess);
VL_ATTR_COLD void Vhello_uvm_uvm_pkg__03a__03auvm_resource__Tz40__Vclpkg___eval_static__TOP__uvm_pkg__03a__03auvm_resource__Tz40__Vclpkg(Vhello_uvm_uvm_pkg__03a__03auvm_resource__Tz40__Vclpkg* vlSelf, VlProcessRef vlProcess);
VL_ATTR_COLD void Vhello_uvm_uvm_pkg__03a__03auvm_object_registry__Tz86__Vclpkg___eval_static__TOP__uvm_pkg__03a__03auvm_object_registry__Tz86__Vclpkg(Vhello_uvm_uvm_pkg__03a__03auvm_object_registry__Tz86__Vclpkg* vlSelf, VlProcessRef vlProcess);
VL_ATTR_COLD void Vhello_uvm_uvm_pkg__03a__03auvm_object_registry__Tz87__Vclpkg___eval_static__TOP__uvm_pkg__03a__03auvm_object_registry__Tz87__Vclpkg(Vhello_uvm_uvm_pkg__03a__03auvm_object_registry__Tz87__Vclpkg* vlSelf, VlProcessRef vlProcess);
VL_ATTR_COLD void Vhello_uvm_uvm_pkg__03a__03auvm_object_registry__Tz88__Vclpkg___eval_static__TOP__uvm_pkg__03a__03auvm_object_registry__Tz88__Vclpkg(Vhello_uvm_uvm_pkg__03a__03auvm_object_registry__Tz88__Vclpkg* vlSelf, VlProcessRef vlProcess);
VL_ATTR_COLD void Vhello_uvm_uvm_pkg__03a__03auvm_object_registry__Tz89__Vclpkg___eval_static__TOP__uvm_pkg__03a__03auvm_object_registry__Tz89__Vclpkg(Vhello_uvm_uvm_pkg__03a__03auvm_object_registry__Tz89__Vclpkg* vlSelf, VlProcessRef vlProcess);
VL_ATTR_COLD void Vhello_uvm_uvm_pkg__03a__03auvm_component_registry__Tz93__Vclpkg___eval_static__TOP__uvm_pkg__03a__03auvm_component_registry__Tz93__Vclpkg(Vhello_uvm_uvm_pkg__03a__03auvm_component_registry__Tz93__Vclpkg* vlSelf, VlProcessRef vlProcess);
VL_ATTR_COLD void Vhello_uvm_uvm_pkg__03a__03auvm_table_printer__Vclpkg___eval_static__TOP__uvm_pkg__03a__03auvm_table_printer__Vclpkg(Vhello_uvm_uvm_pkg__03a__03auvm_table_printer__Vclpkg* vlSelf);
VL_ATTR_COLD void Vhello_uvm_uvm_pkg__03a__03auvm_callback__Vclpkg___eval_static__TOP__uvm_pkg__03a__03auvm_callback__Vclpkg(Vhello_uvm_uvm_pkg__03a__03auvm_callback__Vclpkg* vlSelf, VlProcessRef vlProcess);
VL_ATTR_COLD void Vhello_uvm_uvm_pkg__03a__03auvm_callbacks__Tz7_TBz8__Vclpkg___eval_static__TOP__uvm_pkg__03a__03auvm_callbacks__Tz7_TBz8__Vclpkg(Vhello_uvm_uvm_pkg__03a__03auvm_callbacks__Tz7_TBz8__Vclpkg* vlSelf, VlProcessRef vlProcess);
VL_ATTR_COLD void Vhello_uvm_uvm_pkg__03a__03auvm_callbacks__Tz11_TBz12__Vclpkg___eval_static__TOP__uvm_pkg__03a__03auvm_callbacks__Tz11_TBz12__Vclpkg(Vhello_uvm_uvm_pkg__03a__03auvm_callbacks__Tz11_TBz12__Vclpkg* vlSelf, VlProcessRef vlProcess);
VL_ATTR_COLD void Vhello_uvm_uvm_pkg__03a__03auvm_callbacks__Tz13_TBz14__Vclpkg___eval_static__TOP__uvm_pkg__03a__03auvm_callbacks__Tz13_TBz14__Vclpkg(Vhello_uvm_uvm_pkg__03a__03auvm_callbacks__Tz13_TBz14__Vclpkg* vlSelf, VlProcessRef vlProcess);
VL_ATTR_COLD void Vhello_uvm_uvm_pkg__03a__03auvm_callbacks__Tz13_TBz15__Vclpkg___eval_static__TOP__uvm_pkg__03a__03auvm_callbacks__Tz13_TBz15__Vclpkg(Vhello_uvm_uvm_pkg__03a__03auvm_callbacks__Tz13_TBz15__Vclpkg* vlSelf, VlProcessRef vlProcess);
VL_ATTR_COLD void Vhello_uvm_uvm_pkg__03a__03auvm_callbacks__Tz18_TBz19__Vclpkg___eval_static__TOP__uvm_pkg__03a__03auvm_callbacks__Tz18_TBz19__Vclpkg(Vhello_uvm_uvm_pkg__03a__03auvm_callbacks__Tz18_TBz19__Vclpkg* vlSelf, VlProcessRef vlProcess);
VL_ATTR_COLD void Vhello_uvm_uvm_pkg__03a__03auvm_callbacks__Tz20_TBz19__Vclpkg___eval_static__TOP__uvm_pkg__03a__03auvm_callbacks__Tz20_TBz19__Vclpkg(Vhello_uvm_uvm_pkg__03a__03auvm_callbacks__Tz20_TBz19__Vclpkg* vlSelf, VlProcessRef vlProcess);
VL_ATTR_COLD void Vhello_uvm_uvm_pkg__03a__03auvm_callbacks__Tz21_TBz19__Vclpkg___eval_static__TOP__uvm_pkg__03a__03auvm_callbacks__Tz21_TBz19__Vclpkg(Vhello_uvm_uvm_pkg__03a__03auvm_callbacks__Tz21_TBz19__Vclpkg* vlSelf, VlProcessRef vlProcess);
VL_ATTR_COLD void Vhello_uvm_uvm_pkg__03a__03auvm_callbacks__Tz22_TBz19__Vclpkg___eval_static__TOP__uvm_pkg__03a__03auvm_callbacks__Tz22_TBz19__Vclpkg(Vhello_uvm_uvm_pkg__03a__03auvm_callbacks__Tz22_TBz19__Vclpkg* vlSelf, VlProcessRef vlProcess);
VL_ATTR_COLD void Vhello_uvm_uvm_pkg__03a__03auvm_callbacks__Tz23_TBz24__Vclpkg___eval_static__TOP__uvm_pkg__03a__03auvm_callbacks__Tz23_TBz24__Vclpkg(Vhello_uvm_uvm_pkg__03a__03auvm_callbacks__Tz23_TBz24__Vclpkg* vlSelf, VlProcessRef vlProcess);
VL_ATTR_COLD void Vhello_uvm_uvm_pkg__03a__03auvm_callbacks__Tz25_TBz26__Vclpkg___eval_static__TOP__uvm_pkg__03a__03auvm_callbacks__Tz25_TBz26__Vclpkg(Vhello_uvm_uvm_pkg__03a__03auvm_callbacks__Tz25_TBz26__Vclpkg* vlSelf, VlProcessRef vlProcess);
VL_ATTR_COLD void Vhello_uvm_uvm_pkg__03a__03auvm_callbacks__Tz7__Vclpkg___eval_static__TOP__uvm_pkg__03a__03auvm_callbacks__Tz7__Vclpkg(Vhello_uvm_uvm_pkg__03a__03auvm_callbacks__Tz7__Vclpkg* vlSelf, VlProcessRef vlProcess);
VL_ATTR_COLD void Vhello_uvm_uvm_pkg__03a__03auvm_callbacks__Tz11__Vclpkg___eval_static__TOP__uvm_pkg__03a__03auvm_callbacks__Tz11__Vclpkg(Vhello_uvm_uvm_pkg__03a__03auvm_callbacks__Tz11__Vclpkg* vlSelf, VlProcessRef vlProcess);
VL_ATTR_COLD void Vhello_uvm_uvm_pkg__03a__03auvm_callbacks__Tz13__Vclpkg___eval_static__TOP__uvm_pkg__03a__03auvm_callbacks__Tz13__Vclpkg(Vhello_uvm_uvm_pkg__03a__03auvm_callbacks__Tz13__Vclpkg* vlSelf, VlProcessRef vlProcess);
VL_ATTR_COLD void Vhello_uvm_uvm_pkg__03a__03auvm_callbacks__Tz18__Vclpkg___eval_static__TOP__uvm_pkg__03a__03auvm_callbacks__Tz18__Vclpkg(Vhello_uvm_uvm_pkg__03a__03auvm_callbacks__Tz18__Vclpkg* vlSelf, VlProcessRef vlProcess);
VL_ATTR_COLD void Vhello_uvm_uvm_pkg__03a__03auvm_callbacks__Tz20__Vclpkg___eval_static__TOP__uvm_pkg__03a__03auvm_callbacks__Tz20__Vclpkg(Vhello_uvm_uvm_pkg__03a__03auvm_callbacks__Tz20__Vclpkg* vlSelf, VlProcessRef vlProcess);
VL_ATTR_COLD void Vhello_uvm_uvm_pkg__03a__03auvm_callbacks__Tz21__Vclpkg___eval_static__TOP__uvm_pkg__03a__03auvm_callbacks__Tz21__Vclpkg(Vhello_uvm_uvm_pkg__03a__03auvm_callbacks__Tz21__Vclpkg* vlSelf, VlProcessRef vlProcess);
VL_ATTR_COLD void Vhello_uvm_uvm_pkg__03a__03auvm_callbacks__Tz22__Vclpkg___eval_static__TOP__uvm_pkg__03a__03auvm_callbacks__Tz22__Vclpkg(Vhello_uvm_uvm_pkg__03a__03auvm_callbacks__Tz22__Vclpkg* vlSelf, VlProcessRef vlProcess);
VL_ATTR_COLD void Vhello_uvm_uvm_pkg__03a__03auvm_callbacks__Tz23__Vclpkg___eval_static__TOP__uvm_pkg__03a__03auvm_callbacks__Tz23__Vclpkg(Vhello_uvm_uvm_pkg__03a__03auvm_callbacks__Tz23__Vclpkg* vlSelf, VlProcessRef vlProcess);
VL_ATTR_COLD void Vhello_uvm_uvm_pkg__03a__03auvm_callbacks__Tz25__Vclpkg___eval_static__TOP__uvm_pkg__03a__03auvm_callbacks__Tz25__Vclpkg(Vhello_uvm_uvm_pkg__03a__03auvm_callbacks__Tz25__Vclpkg* vlSelf, VlProcessRef vlProcess);
VL_ATTR_COLD void Vhello_uvm_uvm_pkg__03a__03auvm_report_catcher__Vclpkg___eval_static__TOP__uvm_pkg__03a__03auvm_report_catcher__Vclpkg(Vhello_uvm_uvm_pkg__03a__03auvm_report_catcher__Vclpkg* vlSelf, VlProcessRef vlProcess);
VL_ATTR_COLD void Vhello_uvm_uvm_pkg__03a__03auvm_phase__Vclpkg___eval_static__TOP__uvm_pkg__03a__03auvm_phase__Vclpkg(Vhello_uvm_uvm_pkg__03a__03auvm_phase__Vclpkg* vlSelf, VlProcessRef vlProcess);
VL_ATTR_COLD void Vhello_uvm_uvm_pkg__03a__03auvm_component__Vclpkg___eval_static__TOP__uvm_pkg__03a__03auvm_component__Vclpkg(Vhello_uvm_uvm_pkg__03a__03auvm_component__Vclpkg* vlSelf);
VL_ATTR_COLD void Vhello_uvm_uvm_pkg__03a__03auvm_root__Vclpkg___eval_static__TOP__uvm_pkg__03a__03auvm_root__Vclpkg(Vhello_uvm_uvm_pkg__03a__03auvm_root__Vclpkg* vlSelf);
VL_ATTR_COLD void Vhello_uvm_uvm_pkg__03a__03auvm_objection__Vclpkg___eval_static__TOP__uvm_pkg__03a__03auvm_objection__Vclpkg(Vhello_uvm_uvm_pkg__03a__03auvm_objection__Vclpkg* vlSelf, VlProcessRef vlProcess);
VL_ATTR_COLD void Vhello_uvm_uvm_pkg__03a__03auvm_port_base__Tz81__Vclpkg___eval_static__TOP__uvm_pkg__03a__03auvm_port_base__Tz81__Vclpkg(Vhello_uvm_uvm_pkg__03a__03auvm_port_base__Tz81__Vclpkg* vlSelf);
VL_ATTR_COLD void Vhello_uvm_uvm_pkg__03a__03auvm_port_base__Tz82__Vclpkg___eval_static__TOP__uvm_pkg__03a__03auvm_port_base__Tz82__Vclpkg(Vhello_uvm_uvm_pkg__03a__03auvm_port_base__Tz82__Vclpkg* vlSelf);
VL_ATTR_COLD void Vhello_uvm_uvm_pkg__03a__03auvm_port_base__Tz94__Vclpkg___eval_static__TOP__uvm_pkg__03a__03auvm_port_base__Tz94__Vclpkg(Vhello_uvm_uvm_pkg__03a__03auvm_port_base__Tz94__Vclpkg* vlSelf);
VL_ATTR_COLD void Vhello_uvm_uvm_pkg__03a__03auvm_port_base__Tz97__Vclpkg___eval_static__TOP__uvm_pkg__03a__03auvm_port_base__Tz97__Vclpkg(Vhello_uvm_uvm_pkg__03a__03auvm_port_base__Tz97__Vclpkg* vlSelf);
VL_ATTR_COLD void Vhello_uvm_uvm_pkg__03a__03auvm_sequencer_base__Vclpkg___eval_static__TOP__uvm_pkg__03a__03auvm_sequencer_base__Vclpkg(Vhello_uvm_uvm_pkg__03a__03auvm_sequencer_base__Vclpkg* vlSelf);
VL_ATTR_COLD void Vhello_uvm_uvm_pkg__03a__03auvm_tlm_time__Vclpkg___eval_static__TOP__uvm_pkg__03a__03auvm_tlm_time__Vclpkg(Vhello_uvm_uvm_pkg__03a__03auvm_tlm_time__Vclpkg* vlSelf);
VL_ATTR_COLD void Vhello_uvm_uvm_pkg__03a__03auvm_reg_backdoor__Vclpkg___eval_static__TOP__uvm_pkg__03a__03auvm_reg_backdoor__Vclpkg(Vhello_uvm_uvm_pkg__03a__03auvm_reg_backdoor__Vclpkg* vlSelf, VlProcessRef vlProcess);
VL_ATTR_COLD void Vhello_uvm_uvm_pkg__03a__03auvm_reg_field__Vclpkg___eval_static__TOP__uvm_pkg__03a__03auvm_reg_field__Vclpkg(Vhello_uvm_uvm_pkg__03a__03auvm_reg_field__Vclpkg* vlSelf, VlProcessRef vlProcess);
VL_ATTR_COLD void Vhello_uvm_uvm_pkg__03a__03auvm_vreg_field__Vclpkg___eval_static__TOP__uvm_pkg__03a__03auvm_vreg_field__Vclpkg(Vhello_uvm_uvm_pkg__03a__03auvm_vreg_field__Vclpkg* vlSelf, VlProcessRef vlProcess);
VL_ATTR_COLD void Vhello_uvm_uvm_pkg__03a__03auvm_reg__Vclpkg___eval_static__TOP__uvm_pkg__03a__03auvm_reg__Vclpkg(Vhello_uvm_uvm_pkg__03a__03auvm_reg__Vclpkg* vlSelf, VlProcessRef vlProcess);
VL_ATTR_COLD void Vhello_uvm_uvm_pkg__03a__03auvm_vreg__Vclpkg___eval_static__TOP__uvm_pkg__03a__03auvm_vreg__Vclpkg(Vhello_uvm_uvm_pkg__03a__03auvm_vreg__Vclpkg* vlSelf, VlProcessRef vlProcess);
VL_ATTR_COLD void Vhello_uvm_uvm_pkg__03a__03auvm_mem__Vclpkg___eval_static__TOP__uvm_pkg__03a__03auvm_mem__Vclpkg(Vhello_uvm_uvm_pkg__03a__03auvm_mem__Vclpkg* vlSelf, VlProcessRef vlProcess);
void Vhello_uvm___024root___timing_ready(Vhello_uvm___024root* vlSelf);

VL_ATTR_COLD void Vhello_uvm___024root___eval_static(Vhello_uvm___024root* vlSelf) {
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vhello_uvm___024root___eval_static\n"); );
    Vhello_uvm__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    auto& vlSelfRef = std::ref(*vlSelf).get();
    // Body
    VlProcessRef vlProcess = std::make_shared<VlProcess>();
    VlProcess::currentp(vlProcess.get());
    Vhello_uvm_uvm_pkg___eval_static__TOP__uvm_pkg((&vlSymsp->TOP__uvm_pkg), vlProcess);
    Vhello_uvm_uvm_pkg__03a__03auvm_object__Vclpkg___eval_static__TOP__uvm_pkg__03a__03auvm_object__Vclpkg((&vlSymsp->TOP__uvm_pkg__03a__03auvm_object__Vclpkg));
    Vhello_uvm_uvm_pkg__03a__03auvm_resource_options__Vclpkg___eval_static__TOP__uvm_pkg__03a__03auvm_resource_options__Vclpkg((&vlSymsp->TOP__uvm_pkg__03a__03auvm_resource_options__Vclpkg));
    Vhello_uvm_uvm_pkg__03a__03auvm_resource_pool__Vclpkg___eval_static__TOP__uvm_pkg__03a__03auvm_resource_pool__Vclpkg((&vlSymsp->TOP__uvm_pkg__03a__03auvm_resource_pool__Vclpkg));
    Vhello_uvm_uvm_pkg__03a__03auvm_resource__Tz1__Vclpkg___eval_static__TOP__uvm_pkg__03a__03auvm_resource__Tz1__Vclpkg((&vlSymsp->TOP__uvm_pkg__03a__03auvm_resource__Tz1__Vclpkg), vlProcess);
    Vhello_uvm_uvm_pkg__03a__03auvm_resource__Tz4__Vclpkg___eval_static__TOP__uvm_pkg__03a__03auvm_resource__Tz4__Vclpkg((&vlSymsp->TOP__uvm_pkg__03a__03auvm_resource__Tz4__Vclpkg), vlProcess);
    Vhello_uvm_uvm_pkg__03a__03auvm_resource__Tz5__Vclpkg___eval_static__TOP__uvm_pkg__03a__03auvm_resource__Tz5__Vclpkg((&vlSymsp->TOP__uvm_pkg__03a__03auvm_resource__Tz5__Vclpkg), vlProcess);
    Vhello_uvm_uvm_pkg__03a__03auvm_resource__Tz6__Vclpkg___eval_static__TOP__uvm_pkg__03a__03auvm_resource__Tz6__Vclpkg((&vlSymsp->TOP__uvm_pkg__03a__03auvm_resource__Tz6__Vclpkg), vlProcess);
    Vhello_uvm_uvm_pkg__03a__03auvm_object_registry__pi1__Vclpkg___eval_static__TOP__uvm_pkg__03a__03auvm_object_registry__pi1__Vclpkg((&vlSymsp->TOP__uvm_pkg__03a__03auvm_object_registry__pi1__Vclpkg), vlProcess);
    Vhello_uvm_uvm_pkg__03a__03auvm_object_registry__pi2__Vclpkg___eval_static__TOP__uvm_pkg__03a__03auvm_object_registry__pi2__Vclpkg((&vlSymsp->TOP__uvm_pkg__03a__03auvm_object_registry__pi2__Vclpkg), vlProcess);
    Vhello_uvm_uvm_pkg__03a__03auvm_object_registry__pi3__Vclpkg___eval_static__TOP__uvm_pkg__03a__03auvm_object_registry__pi3__Vclpkg((&vlSymsp->TOP__uvm_pkg__03a__03auvm_object_registry__pi3__Vclpkg), vlProcess);
    Vhello_uvm_uvm_pkg__03a__03auvm_resource__Tz16__Vclpkg___eval_static__TOP__uvm_pkg__03a__03auvm_resource__Tz16__Vclpkg((&vlSymsp->TOP__uvm_pkg__03a__03auvm_resource__Tz16__Vclpkg), vlProcess);
    Vhello_uvm_uvm_pkg__03a__03auvm_object_registry__pi4__Vclpkg___eval_static__TOP__uvm_pkg__03a__03auvm_object_registry__pi4__Vclpkg((&vlSymsp->TOP__uvm_pkg__03a__03auvm_object_registry__pi4__Vclpkg), vlProcess);
    Vhello_uvm_uvm_pkg__03a__03auvm_component_registry__Tz44__Vclpkg___eval_static__TOP__uvm_pkg__03a__03auvm_component_registry__Tz44__Vclpkg((&vlSymsp->TOP__uvm_pkg__03a__03auvm_component_registry__Tz44__Vclpkg), vlProcess);
    Vhello_uvm_uvm_pkg__03a__03auvm_object_registry__pi7__Vclpkg___eval_static__TOP__uvm_pkg__03a__03auvm_object_registry__pi7__Vclpkg((&vlSymsp->TOP__uvm_pkg__03a__03auvm_object_registry__pi7__Vclpkg), vlProcess);
    Vhello_uvm_uvm_pkg__03a__03auvm_resource__Tz17__Vclpkg___eval_static__TOP__uvm_pkg__03a__03auvm_resource__Tz17__Vclpkg((&vlSymsp->TOP__uvm_pkg__03a__03auvm_resource__Tz17__Vclpkg), vlProcess);
    Vhello_uvm_uvm_pkg__03a__03auvm_object_registry__pi8__Vclpkg___eval_static__TOP__uvm_pkg__03a__03auvm_object_registry__pi8__Vclpkg((&vlSymsp->TOP__uvm_pkg__03a__03auvm_object_registry__pi8__Vclpkg), vlProcess);
    Vhello_uvm_uvm_pkg__03a__03auvm_object_registry__pi9__Vclpkg___eval_static__TOP__uvm_pkg__03a__03auvm_object_registry__pi9__Vclpkg((&vlSymsp->TOP__uvm_pkg__03a__03auvm_object_registry__pi9__Vclpkg), vlProcess);
    Vhello_uvm_uvm_pkg__03a__03auvm_object_registry__pi10__Vclpkg___eval_static__TOP__uvm_pkg__03a__03auvm_object_registry__pi10__Vclpkg((&vlSymsp->TOP__uvm_pkg__03a__03auvm_object_registry__pi10__Vclpkg), vlProcess);
    Vhello_uvm_uvm_pkg__03a__03auvm_resource__Tz53__Vclpkg___eval_static__TOP__uvm_pkg__03a__03auvm_resource__Tz53__Vclpkg((&vlSymsp->TOP__uvm_pkg__03a__03auvm_resource__Tz53__Vclpkg), vlProcess);
    Vhello_uvm_uvm_pkg__03a__03auvm_resource___Vclpkg___eval_static__TOP__uvm_pkg__03a__03auvm_resource___Vclpkg((&vlSymsp->TOP__uvm_pkg__03a__03auvm_resource___Vclpkg), vlProcess);
    Vhello_uvm_uvm_pkg__03a__03auvm_resource__Tz54__Vclpkg___eval_static__TOP__uvm_pkg__03a__03auvm_resource__Tz54__Vclpkg((&vlSymsp->TOP__uvm_pkg__03a__03auvm_resource__Tz54__Vclpkg), vlProcess);
    Vhello_uvm_uvm_pkg__03a__03auvm_resource__Tz55__Vclpkg___eval_static__TOP__uvm_pkg__03a__03auvm_resource__Tz55__Vclpkg((&vlSymsp->TOP__uvm_pkg__03a__03auvm_resource__Tz55__Vclpkg), vlProcess);
    Vhello_uvm_uvm_pkg__03a__03auvm_resource__Tz52__Vclpkg___eval_static__TOP__uvm_pkg__03a__03auvm_resource__Tz52__Vclpkg((&vlSymsp->TOP__uvm_pkg__03a__03auvm_resource__Tz52__Vclpkg), vlProcess);
    Vhello_uvm_uvm_pkg__03a__03auvm_object_registry__pi11__Vclpkg___eval_static__TOP__uvm_pkg__03a__03auvm_object_registry__pi11__Vclpkg((&vlSymsp->TOP__uvm_pkg__03a__03auvm_object_registry__pi11__Vclpkg), vlProcess);
    Vhello_uvm_uvm_pkg__03a__03auvm_object_registry__pi12__Vclpkg___eval_static__TOP__uvm_pkg__03a__03auvm_object_registry__pi12__Vclpkg((&vlSymsp->TOP__uvm_pkg__03a__03auvm_object_registry__pi12__Vclpkg), vlProcess);
    Vhello_uvm_uvm_pkg__03a__03auvm_object_registry__pi13__Vclpkg___eval_static__TOP__uvm_pkg__03a__03auvm_object_registry__pi13__Vclpkg((&vlSymsp->TOP__uvm_pkg__03a__03auvm_object_registry__pi13__Vclpkg), vlProcess);
    Vhello_uvm_uvm_pkg__03a__03auvm_resource__Tz66__Vclpkg___eval_static__TOP__uvm_pkg__03a__03auvm_resource__Tz66__Vclpkg((&vlSymsp->TOP__uvm_pkg__03a__03auvm_resource__Tz66__Vclpkg), vlProcess);
    Vhello_uvm_uvm_pkg__03a__03auvm_object_registry__pi14__Vclpkg___eval_static__TOP__uvm_pkg__03a__03auvm_object_registry__pi14__Vclpkg((&vlSymsp->TOP__uvm_pkg__03a__03auvm_object_registry__pi14__Vclpkg), vlProcess);
    Vhello_uvm_uvm_pkg__03a__03auvm_object_registry__pi15__Vclpkg___eval_static__TOP__uvm_pkg__03a__03auvm_object_registry__pi15__Vclpkg((&vlSymsp->TOP__uvm_pkg__03a__03auvm_object_registry__pi15__Vclpkg), vlProcess);
    Vhello_uvm_uvm_pkg__03a__03auvm_object_registry__pi16__Vclpkg___eval_static__TOP__uvm_pkg__03a__03auvm_object_registry__pi16__Vclpkg((&vlSymsp->TOP__uvm_pkg__03a__03auvm_object_registry__pi16__Vclpkg), vlProcess);
    Vhello_uvm_uvm_pkg__03a__03auvm_object_registry__pi17__Vclpkg___eval_static__TOP__uvm_pkg__03a__03auvm_object_registry__pi17__Vclpkg((&vlSymsp->TOP__uvm_pkg__03a__03auvm_object_registry__pi17__Vclpkg), vlProcess);
    Vhello_uvm_uvm_pkg__03a__03auvm_object_registry__pi18__Vclpkg___eval_static__TOP__uvm_pkg__03a__03auvm_object_registry__pi18__Vclpkg((&vlSymsp->TOP__uvm_pkg__03a__03auvm_object_registry__pi18__Vclpkg), vlProcess);
    Vhello_uvm_uvm_pkg__03a__03auvm_object_registry__pi19__Vclpkg___eval_static__TOP__uvm_pkg__03a__03auvm_object_registry__pi19__Vclpkg((&vlSymsp->TOP__uvm_pkg__03a__03auvm_object_registry__pi19__Vclpkg), vlProcess);
    Vhello_uvm_uvm_pkg__03a__03auvm_object_registry__pi23__Vclpkg___eval_static__TOP__uvm_pkg__03a__03auvm_object_registry__pi23__Vclpkg((&vlSymsp->TOP__uvm_pkg__03a__03auvm_object_registry__pi23__Vclpkg), vlProcess);
    Vhello_uvm_uvm_pkg__03a__03auvm_object_registry__pi24__Vclpkg___eval_static__TOP__uvm_pkg__03a__03auvm_object_registry__pi24__Vclpkg((&vlSymsp->TOP__uvm_pkg__03a__03auvm_object_registry__pi24__Vclpkg), vlProcess);
    Vhello_uvm_uvm_pkg__03a__03auvm_object_registry__pi25__Vclpkg___eval_static__TOP__uvm_pkg__03a__03auvm_object_registry__pi25__Vclpkg((&vlSymsp->TOP__uvm_pkg__03a__03auvm_object_registry__pi25__Vclpkg), vlProcess);
    Vhello_uvm_uvm_pkg__03a__03auvm_object_registry__pi26__Vclpkg___eval_static__TOP__uvm_pkg__03a__03auvm_object_registry__pi26__Vclpkg((&vlSymsp->TOP__uvm_pkg__03a__03auvm_object_registry__pi26__Vclpkg), vlProcess);
    Vhello_uvm_uvm_pkg__03a__03auvm_object_registry__pi27__Vclpkg___eval_static__TOP__uvm_pkg__03a__03auvm_object_registry__pi27__Vclpkg((&vlSymsp->TOP__uvm_pkg__03a__03auvm_object_registry__pi27__Vclpkg), vlProcess);
    Vhello_uvm_uvm_pkg__03a__03auvm_object_registry__pi28__Vclpkg___eval_static__TOP__uvm_pkg__03a__03auvm_object_registry__pi28__Vclpkg((&vlSymsp->TOP__uvm_pkg__03a__03auvm_object_registry__pi28__Vclpkg), vlProcess);
    Vhello_uvm_uvm_pkg__03a__03auvm_object_registry__pi29__Vclpkg___eval_static__TOP__uvm_pkg__03a__03auvm_object_registry__pi29__Vclpkg((&vlSymsp->TOP__uvm_pkg__03a__03auvm_object_registry__pi29__Vclpkg), vlProcess);
    Vhello_uvm_uvm_pkg__03a__03auvm_object_registry__pi30__Vclpkg___eval_static__TOP__uvm_pkg__03a__03auvm_object_registry__pi30__Vclpkg((&vlSymsp->TOP__uvm_pkg__03a__03auvm_object_registry__pi30__Vclpkg), vlProcess);
    Vhello_uvm_uvm_pkg__03a__03auvm_object_registry__pi31__Vclpkg___eval_static__TOP__uvm_pkg__03a__03auvm_object_registry__pi31__Vclpkg((&vlSymsp->TOP__uvm_pkg__03a__03auvm_object_registry__pi31__Vclpkg), vlProcess);
    Vhello_uvm_uvm_pkg__03a__03auvm_object_registry__pi32__Vclpkg___eval_static__TOP__uvm_pkg__03a__03auvm_object_registry__pi32__Vclpkg((&vlSymsp->TOP__uvm_pkg__03a__03auvm_object_registry__pi32__Vclpkg), vlProcess);
    Vhello_uvm_uvm_pkg__03a__03auvm_object_registry__pi33__Vclpkg___eval_static__TOP__uvm_pkg__03a__03auvm_object_registry__pi33__Vclpkg((&vlSymsp->TOP__uvm_pkg__03a__03auvm_object_registry__pi33__Vclpkg), vlProcess);
    Vhello_uvm_uvm_pkg__03a__03auvm_object_registry__pi34__Vclpkg___eval_static__TOP__uvm_pkg__03a__03auvm_object_registry__pi34__Vclpkg((&vlSymsp->TOP__uvm_pkg__03a__03auvm_object_registry__pi34__Vclpkg), vlProcess);
    Vhello_uvm_uvm_pkg__03a__03auvm_object_registry__pi35__Vclpkg___eval_static__TOP__uvm_pkg__03a__03auvm_object_registry__pi35__Vclpkg((&vlSymsp->TOP__uvm_pkg__03a__03auvm_object_registry__pi35__Vclpkg), vlProcess);
    Vhello_uvm_uvm_pkg__03a__03auvm_object_registry__pi36__Vclpkg___eval_static__TOP__uvm_pkg__03a__03auvm_object_registry__pi36__Vclpkg((&vlSymsp->TOP__uvm_pkg__03a__03auvm_object_registry__pi36__Vclpkg), vlProcess);
    Vhello_uvm_uvm_pkg__03a__03auvm_object_registry__pi37__Vclpkg___eval_static__TOP__uvm_pkg__03a__03auvm_object_registry__pi37__Vclpkg((&vlSymsp->TOP__uvm_pkg__03a__03auvm_object_registry__pi37__Vclpkg), vlProcess);
    Vhello_uvm_uvm_pkg__03a__03auvm_object_registry__pi38__Vclpkg___eval_static__TOP__uvm_pkg__03a__03auvm_object_registry__pi38__Vclpkg((&vlSymsp->TOP__uvm_pkg__03a__03auvm_object_registry__pi38__Vclpkg), vlProcess);
    Vhello_uvm_uvm_pkg__03a__03auvm_object_registry__pi39__Vclpkg___eval_static__TOP__uvm_pkg__03a__03auvm_object_registry__pi39__Vclpkg((&vlSymsp->TOP__uvm_pkg__03a__03auvm_object_registry__pi39__Vclpkg), vlProcess);
    Vhello_uvm_uvm_pkg__03a__03auvm_object_registry__pi40__Vclpkg___eval_static__TOP__uvm_pkg__03a__03auvm_object_registry__pi40__Vclpkg((&vlSymsp->TOP__uvm_pkg__03a__03auvm_object_registry__pi40__Vclpkg), vlProcess);
    Vhello_uvm_uvm_pkg__03a__03auvm_object_registry__pi41__Vclpkg___eval_static__TOP__uvm_pkg__03a__03auvm_object_registry__pi41__Vclpkg((&vlSymsp->TOP__uvm_pkg__03a__03auvm_object_registry__pi41__Vclpkg), vlProcess);
    Vhello_uvm_uvm_pkg__03a__03auvm_object_registry__pi42__Vclpkg___eval_static__TOP__uvm_pkg__03a__03auvm_object_registry__pi42__Vclpkg((&vlSymsp->TOP__uvm_pkg__03a__03auvm_object_registry__pi42__Vclpkg), vlProcess);
    Vhello_uvm_uvm_pkg__03a__03auvm_object_registry__pi43__Vclpkg___eval_static__TOP__uvm_pkg__03a__03auvm_object_registry__pi43__Vclpkg((&vlSymsp->TOP__uvm_pkg__03a__03auvm_object_registry__pi43__Vclpkg), vlProcess);
    Vhello_uvm_uvm_pkg__03a__03auvm_object_registry__pi44__Vclpkg___eval_static__TOP__uvm_pkg__03a__03auvm_object_registry__pi44__Vclpkg((&vlSymsp->TOP__uvm_pkg__03a__03auvm_object_registry__pi44__Vclpkg), vlProcess);
    Vhello_uvm_uvm_pkg__03a__03auvm_object_registry__pi45__Vclpkg___eval_static__TOP__uvm_pkg__03a__03auvm_object_registry__pi45__Vclpkg((&vlSymsp->TOP__uvm_pkg__03a__03auvm_object_registry__pi45__Vclpkg), vlProcess);
    Vhello_uvm_uvm_pkg__03a__03auvm_object_registry__pi46__Vclpkg___eval_static__TOP__uvm_pkg__03a__03auvm_object_registry__pi46__Vclpkg((&vlSymsp->TOP__uvm_pkg__03a__03auvm_object_registry__pi46__Vclpkg), vlProcess);
    Vhello_uvm_uvm_pkg__03a__03auvm_object_registry__Tz79__Vclpkg___eval_static__TOP__uvm_pkg__03a__03auvm_object_registry__Tz79__Vclpkg((&vlSymsp->TOP__uvm_pkg__03a__03auvm_object_registry__Tz79__Vclpkg), vlProcess);
    Vhello_uvm_uvm_pkg__03a__03auvm_object_registry__Tz80__Vclpkg___eval_static__TOP__uvm_pkg__03a__03auvm_object_registry__Tz80__Vclpkg((&vlSymsp->TOP__uvm_pkg__03a__03auvm_object_registry__Tz80__Vclpkg), vlProcess);
    Vhello_uvm_uvm_pkg__03a__03auvm_resource__Tz40__Vclpkg___eval_static__TOP__uvm_pkg__03a__03auvm_resource__Tz40__Vclpkg((&vlSymsp->TOP__uvm_pkg__03a__03auvm_resource__Tz40__Vclpkg), vlProcess);
    Vhello_uvm_uvm_pkg__03a__03auvm_object_registry__Tz86__Vclpkg___eval_static__TOP__uvm_pkg__03a__03auvm_object_registry__Tz86__Vclpkg((&vlSymsp->TOP__uvm_pkg__03a__03auvm_object_registry__Tz86__Vclpkg), vlProcess);
    Vhello_uvm_uvm_pkg__03a__03auvm_object_registry__Tz87__Vclpkg___eval_static__TOP__uvm_pkg__03a__03auvm_object_registry__Tz87__Vclpkg((&vlSymsp->TOP__uvm_pkg__03a__03auvm_object_registry__Tz87__Vclpkg), vlProcess);
    Vhello_uvm_uvm_pkg__03a__03auvm_object_registry__Tz88__Vclpkg___eval_static__TOP__uvm_pkg__03a__03auvm_object_registry__Tz88__Vclpkg((&vlSymsp->TOP__uvm_pkg__03a__03auvm_object_registry__Tz88__Vclpkg), vlProcess);
    Vhello_uvm_uvm_pkg__03a__03auvm_object_registry__Tz89__Vclpkg___eval_static__TOP__uvm_pkg__03a__03auvm_object_registry__Tz89__Vclpkg((&vlSymsp->TOP__uvm_pkg__03a__03auvm_object_registry__Tz89__Vclpkg), vlProcess);
    Vhello_uvm_uvm_pkg__03a__03auvm_component_registry__Tz93__Vclpkg___eval_static__TOP__uvm_pkg__03a__03auvm_component_registry__Tz93__Vclpkg((&vlSymsp->TOP__uvm_pkg__03a__03auvm_component_registry__Tz93__Vclpkg), vlProcess);
    Vhello_uvm_uvm_pkg__03a__03auvm_table_printer__Vclpkg___eval_static__TOP__uvm_pkg__03a__03auvm_table_printer__Vclpkg((&vlSymsp->TOP__uvm_pkg__03a__03auvm_table_printer__Vclpkg));
    Vhello_uvm_uvm_pkg__03a__03auvm_callback__Vclpkg___eval_static__TOP__uvm_pkg__03a__03auvm_callback__Vclpkg((&vlSymsp->TOP__uvm_pkg__03a__03auvm_callback__Vclpkg), vlProcess);
    Vhello_uvm_uvm_pkg__03a__03auvm_callbacks__Tz7_TBz8__Vclpkg___eval_static__TOP__uvm_pkg__03a__03auvm_callbacks__Tz7_TBz8__Vclpkg((&vlSymsp->TOP__uvm_pkg__03a__03auvm_callbacks__Tz7_TBz8__Vclpkg), vlProcess);
    Vhello_uvm_uvm_pkg__03a__03auvm_callbacks__Tz11_TBz12__Vclpkg___eval_static__TOP__uvm_pkg__03a__03auvm_callbacks__Tz11_TBz12__Vclpkg((&vlSymsp->TOP__uvm_pkg__03a__03auvm_callbacks__Tz11_TBz12__Vclpkg), vlProcess);
    Vhello_uvm_uvm_pkg__03a__03auvm_callbacks__Tz13_TBz14__Vclpkg___eval_static__TOP__uvm_pkg__03a__03auvm_callbacks__Tz13_TBz14__Vclpkg((&vlSymsp->TOP__uvm_pkg__03a__03auvm_callbacks__Tz13_TBz14__Vclpkg), vlProcess);
    Vhello_uvm_uvm_pkg__03a__03auvm_callbacks__Tz13_TBz15__Vclpkg___eval_static__TOP__uvm_pkg__03a__03auvm_callbacks__Tz13_TBz15__Vclpkg((&vlSymsp->TOP__uvm_pkg__03a__03auvm_callbacks__Tz13_TBz15__Vclpkg), vlProcess);
    Vhello_uvm_uvm_pkg__03a__03auvm_callbacks__Tz18_TBz19__Vclpkg___eval_static__TOP__uvm_pkg__03a__03auvm_callbacks__Tz18_TBz19__Vclpkg((&vlSymsp->TOP__uvm_pkg__03a__03auvm_callbacks__Tz18_TBz19__Vclpkg), vlProcess);
    Vhello_uvm_uvm_pkg__03a__03auvm_callbacks__Tz20_TBz19__Vclpkg___eval_static__TOP__uvm_pkg__03a__03auvm_callbacks__Tz20_TBz19__Vclpkg((&vlSymsp->TOP__uvm_pkg__03a__03auvm_callbacks__Tz20_TBz19__Vclpkg), vlProcess);
    Vhello_uvm_uvm_pkg__03a__03auvm_callbacks__Tz21_TBz19__Vclpkg___eval_static__TOP__uvm_pkg__03a__03auvm_callbacks__Tz21_TBz19__Vclpkg((&vlSymsp->TOP__uvm_pkg__03a__03auvm_callbacks__Tz21_TBz19__Vclpkg), vlProcess);
    Vhello_uvm_uvm_pkg__03a__03auvm_callbacks__Tz22_TBz19__Vclpkg___eval_static__TOP__uvm_pkg__03a__03auvm_callbacks__Tz22_TBz19__Vclpkg((&vlSymsp->TOP__uvm_pkg__03a__03auvm_callbacks__Tz22_TBz19__Vclpkg), vlProcess);
    Vhello_uvm_uvm_pkg__03a__03auvm_callbacks__Tz23_TBz24__Vclpkg___eval_static__TOP__uvm_pkg__03a__03auvm_callbacks__Tz23_TBz24__Vclpkg((&vlSymsp->TOP__uvm_pkg__03a__03auvm_callbacks__Tz23_TBz24__Vclpkg), vlProcess);
    Vhello_uvm_uvm_pkg__03a__03auvm_callbacks__Tz25_TBz26__Vclpkg___eval_static__TOP__uvm_pkg__03a__03auvm_callbacks__Tz25_TBz26__Vclpkg((&vlSymsp->TOP__uvm_pkg__03a__03auvm_callbacks__Tz25_TBz26__Vclpkg), vlProcess);
    Vhello_uvm_uvm_pkg__03a__03auvm_callbacks__Tz7__Vclpkg___eval_static__TOP__uvm_pkg__03a__03auvm_callbacks__Tz7__Vclpkg((&vlSymsp->TOP__uvm_pkg__03a__03auvm_callbacks__Tz7__Vclpkg), vlProcess);
    Vhello_uvm_uvm_pkg__03a__03auvm_callbacks__Tz11__Vclpkg___eval_static__TOP__uvm_pkg__03a__03auvm_callbacks__Tz11__Vclpkg((&vlSymsp->TOP__uvm_pkg__03a__03auvm_callbacks__Tz11__Vclpkg), vlProcess);
    Vhello_uvm_uvm_pkg__03a__03auvm_callbacks__Tz13__Vclpkg___eval_static__TOP__uvm_pkg__03a__03auvm_callbacks__Tz13__Vclpkg((&vlSymsp->TOP__uvm_pkg__03a__03auvm_callbacks__Tz13__Vclpkg), vlProcess);
    Vhello_uvm_uvm_pkg__03a__03auvm_callbacks__Tz18__Vclpkg___eval_static__TOP__uvm_pkg__03a__03auvm_callbacks__Tz18__Vclpkg((&vlSymsp->TOP__uvm_pkg__03a__03auvm_callbacks__Tz18__Vclpkg), vlProcess);
    Vhello_uvm_uvm_pkg__03a__03auvm_callbacks__Tz20__Vclpkg___eval_static__TOP__uvm_pkg__03a__03auvm_callbacks__Tz20__Vclpkg((&vlSymsp->TOP__uvm_pkg__03a__03auvm_callbacks__Tz20__Vclpkg), vlProcess);
    Vhello_uvm_uvm_pkg__03a__03auvm_callbacks__Tz21__Vclpkg___eval_static__TOP__uvm_pkg__03a__03auvm_callbacks__Tz21__Vclpkg((&vlSymsp->TOP__uvm_pkg__03a__03auvm_callbacks__Tz21__Vclpkg), vlProcess);
    Vhello_uvm_uvm_pkg__03a__03auvm_callbacks__Tz22__Vclpkg___eval_static__TOP__uvm_pkg__03a__03auvm_callbacks__Tz22__Vclpkg((&vlSymsp->TOP__uvm_pkg__03a__03auvm_callbacks__Tz22__Vclpkg), vlProcess);
    Vhello_uvm_uvm_pkg__03a__03auvm_callbacks__Tz23__Vclpkg___eval_static__TOP__uvm_pkg__03a__03auvm_callbacks__Tz23__Vclpkg((&vlSymsp->TOP__uvm_pkg__03a__03auvm_callbacks__Tz23__Vclpkg), vlProcess);
    Vhello_uvm_uvm_pkg__03a__03auvm_callbacks__Tz25__Vclpkg___eval_static__TOP__uvm_pkg__03a__03auvm_callbacks__Tz25__Vclpkg((&vlSymsp->TOP__uvm_pkg__03a__03auvm_callbacks__Tz25__Vclpkg), vlProcess);
    Vhello_uvm_uvm_pkg__03a__03auvm_report_catcher__Vclpkg___eval_static__TOP__uvm_pkg__03a__03auvm_report_catcher__Vclpkg((&vlSymsp->TOP__uvm_pkg__03a__03auvm_report_catcher__Vclpkg), vlProcess);
    Vhello_uvm_uvm_pkg__03a__03auvm_phase__Vclpkg___eval_static__TOP__uvm_pkg__03a__03auvm_phase__Vclpkg((&vlSymsp->TOP__uvm_pkg__03a__03auvm_phase__Vclpkg), vlProcess);
    Vhello_uvm_uvm_pkg__03a__03auvm_component__Vclpkg___eval_static__TOP__uvm_pkg__03a__03auvm_component__Vclpkg((&vlSymsp->TOP__uvm_pkg__03a__03auvm_component__Vclpkg));
    Vhello_uvm_uvm_pkg__03a__03auvm_root__Vclpkg___eval_static__TOP__uvm_pkg__03a__03auvm_root__Vclpkg((&vlSymsp->TOP__uvm_pkg__03a__03auvm_root__Vclpkg));
    Vhello_uvm_uvm_pkg__03a__03auvm_objection__Vclpkg___eval_static__TOP__uvm_pkg__03a__03auvm_objection__Vclpkg((&vlSymsp->TOP__uvm_pkg__03a__03auvm_objection__Vclpkg), vlProcess);
    Vhello_uvm_uvm_pkg__03a__03auvm_port_base__Tz81__Vclpkg___eval_static__TOP__uvm_pkg__03a__03auvm_port_base__Tz81__Vclpkg((&vlSymsp->TOP__uvm_pkg__03a__03auvm_port_base__Tz81__Vclpkg));
    Vhello_uvm_uvm_pkg__03a__03auvm_port_base__Tz82__Vclpkg___eval_static__TOP__uvm_pkg__03a__03auvm_port_base__Tz82__Vclpkg((&vlSymsp->TOP__uvm_pkg__03a__03auvm_port_base__Tz82__Vclpkg));
    Vhello_uvm_uvm_pkg__03a__03auvm_port_base__Tz94__Vclpkg___eval_static__TOP__uvm_pkg__03a__03auvm_port_base__Tz94__Vclpkg((&vlSymsp->TOP__uvm_pkg__03a__03auvm_port_base__Tz94__Vclpkg));
    Vhello_uvm_uvm_pkg__03a__03auvm_port_base__Tz97__Vclpkg___eval_static__TOP__uvm_pkg__03a__03auvm_port_base__Tz97__Vclpkg((&vlSymsp->TOP__uvm_pkg__03a__03auvm_port_base__Tz97__Vclpkg));
    Vhello_uvm_uvm_pkg__03a__03auvm_sequencer_base__Vclpkg___eval_static__TOP__uvm_pkg__03a__03auvm_sequencer_base__Vclpkg((&vlSymsp->TOP__uvm_pkg__03a__03auvm_sequencer_base__Vclpkg));
    Vhello_uvm_uvm_pkg__03a__03auvm_tlm_time__Vclpkg___eval_static__TOP__uvm_pkg__03a__03auvm_tlm_time__Vclpkg((&vlSymsp->TOP__uvm_pkg__03a__03auvm_tlm_time__Vclpkg));
    Vhello_uvm_uvm_pkg__03a__03auvm_reg_backdoor__Vclpkg___eval_static__TOP__uvm_pkg__03a__03auvm_reg_backdoor__Vclpkg((&vlSymsp->TOP__uvm_pkg__03a__03auvm_reg_backdoor__Vclpkg), vlProcess);
    Vhello_uvm_uvm_pkg__03a__03auvm_reg_field__Vclpkg___eval_static__TOP__uvm_pkg__03a__03auvm_reg_field__Vclpkg((&vlSymsp->TOP__uvm_pkg__03a__03auvm_reg_field__Vclpkg), vlProcess);
    Vhello_uvm_uvm_pkg__03a__03auvm_vreg_field__Vclpkg___eval_static__TOP__uvm_pkg__03a__03auvm_vreg_field__Vclpkg((&vlSymsp->TOP__uvm_pkg__03a__03auvm_vreg_field__Vclpkg), vlProcess);
    Vhello_uvm_uvm_pkg__03a__03auvm_reg__Vclpkg___eval_static__TOP__uvm_pkg__03a__03auvm_reg__Vclpkg((&vlSymsp->TOP__uvm_pkg__03a__03auvm_reg__Vclpkg), vlProcess);
    Vhello_uvm_uvm_pkg__03a__03auvm_vreg__Vclpkg___eval_static__TOP__uvm_pkg__03a__03auvm_vreg__Vclpkg((&vlSymsp->TOP__uvm_pkg__03a__03auvm_vreg__Vclpkg), vlProcess);
    Vhello_uvm_uvm_pkg__03a__03auvm_mem__Vclpkg___eval_static__TOP__uvm_pkg__03a__03auvm_mem__Vclpkg((&vlSymsp->TOP__uvm_pkg__03a__03auvm_mem__Vclpkg), vlProcess);
    vlSelfRef.__VactTriggered[0U] = (4ULL | vlSelfRef.__VactTriggered[0U]);
    vlSelfRef.__Vtrigprevexpr_hcb469948__1 = (0U != vlSymsp->TOP__uvm_pkg__03a__03auvm_objection__Vclpkg.__PVT__m_scheduled_list.size());
    Vhello_uvm___024root___timing_ready(vlSelf);
    do {
        vlSelfRef.__VactTriggeredAcc[vlSelfRef.__Vi] 
            = vlSelfRef.__VactTriggered[vlSelfRef.__Vi];
        vlSelfRef.__Vi = ((IData)(1U) + vlSelfRef.__Vi);
    } while ((0U >= vlSelfRef.__Vi));
}

VL_ATTR_COLD void Vhello_uvm___024root___eval_initial__TOP(Vhello_uvm___024root* vlSelf, VlProcessRef vlProcess);

VL_ATTR_COLD void Vhello_uvm___024root___eval_initial(Vhello_uvm___024root* vlSelf) {
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vhello_uvm___024root___eval_initial\n"); );
    Vhello_uvm__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    auto& vlSelfRef = std::ref(*vlSelf).get();
    // Body
    VlProcessRef vlProcess = std::make_shared<VlProcess>();
    VlProcess::currentp(vlProcess.get());
    Vhello_uvm___024root___eval_initial__TOP(vlSelf, vlProcess);
}

VL_ATTR_COLD void Vhello_uvm___024root___eval_initial__TOP(Vhello_uvm___024root* vlSelf, VlProcessRef vlProcess) {
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vhello_uvm___024root___eval_initial__TOP\n"); );
    Vhello_uvm__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    auto& vlSelfRef = std::ref(*vlSelf).get();
    // Locals
    IData/*31:0*/ __Vfunc_uvm_report_enabled__0__verbosity;
    __Vfunc_uvm_report_enabled__0__verbosity = 0;
    CData/*1:0*/ __Vfunc_uvm_report_enabled__0__severity;
    __Vfunc_uvm_report_enabled__0__severity = 0;
    VlClassRef<Vhello_uvm_uvm_pkg__03a__03auvm_coreservice_t> __Vfunc_get__1__Vfuncout;
    VlClassRef<Vhello_uvm_uvm_pkg__03a__03auvm_root> __Vtask_get_root__2__Vfuncout;
    IData/*31:0*/ __Vtask_uvm_report_info__4__verbosity;
    __Vtask_uvm_report_info__4__verbosity = 0;
    IData/*31:0*/ __Vtask_uvm_report_info__4__line;
    __Vtask_uvm_report_info__4__line = 0;
    CData/*0:0*/ __Vtask_uvm_report_info__4__report_enabled_checked;
    __Vtask_uvm_report_info__4__report_enabled_checked = 0;
    VlClassRef<Vhello_uvm_uvm_pkg__03a__03auvm_coreservice_t> __Vfunc_get__5__Vfuncout;
    VlClassRef<Vhello_uvm_uvm_pkg__03a__03auvm_root> __Vtask_get_root__6__Vfuncout;
    // Body
    VlProcess::currentp(vlProcess.get());
    vlSelfRef.__Vfunc_uvm_report_enabled__0__id = "UVM_SETUP"s;
    __Vfunc_uvm_report_enabled__0__severity = 0U;
    __Vfunc_uvm_report_enabled__0__verbosity = 0x00000064U;
    vlSymsp->TOP__uvm_pkg__03a__03auvm_coreservice_t__Vclpkg.__VnoInFunc_get(vlSymsp, __Vfunc_get__1__Vfuncout);
    vlSymsp->TOP__uvm_pkg.uvm_report_enabled__Vstatic__cs 
        = __Vfunc_get__1__Vfuncout;
    VL_NULL_CHECK(vlSymsp->TOP__uvm_pkg.uvm_report_enabled__Vstatic__cs, "../../uvm/distrib/src/base/uvm_globals.svh", 138)->__VnoInFunc_get_root(vlProcess, vlSymsp, __Vtask_get_root__2__Vfuncout);
    vlSymsp->TOP__uvm_pkg.uvm_report_enabled__Vstatic__top 
        = __Vtask_get_root__2__Vfuncout;
    VL_NULL_CHECK(vlSymsp->TOP__uvm_pkg.uvm_report_enabled__Vstatic__top, "../../uvm/distrib/src/base/uvm_globals.svh", 139)->__VnoInFunc_uvm_report_enabled(vlSymsp, __Vfunc_uvm_report_enabled__0__verbosity, (IData)(__Vfunc_uvm_report_enabled__0__severity), vlSelfRef.__Vfunc_uvm_report_enabled__0__id, vlSelfRef.hello_uvm__DOT____VlemCall_0__uvm_report_enabled);
    if ((0U != vlSelfRef.hello_uvm__DOT____VlemCall_0__uvm_report_enabled)) {
        __Vtask_uvm_report_info__4__report_enabled_checked = 1U;
        vlSelfRef.__Vtask_uvm_report_info__4__context_name = ""s;
        __Vtask_uvm_report_info__4__line = 6U;
        vlSelfRef.__Vtask_uvm_report_info__4__filename = "hello_uvm.sv"s;
        __Vtask_uvm_report_info__4__verbosity = 0x00000064U;
        vlSelfRef.__Vtask_uvm_report_info__4__message = "SUCCESS! The UVM environment is ready and running with Verilator."s;
        vlSelfRef.__Vtask_uvm_report_info__4__id = "UVM_SETUP"s;
        vlSymsp->TOP__uvm_pkg__03a__03auvm_coreservice_t__Vclpkg.__VnoInFunc_get(vlSymsp, __Vfunc_get__5__Vfuncout);
        vlSymsp->TOP__uvm_pkg.uvm_report_info__Vstatic__cs 
            = __Vfunc_get__5__Vfuncout;
        VL_NULL_CHECK(vlSymsp->TOP__uvm_pkg.uvm_report_info__Vstatic__cs, "../../uvm/distrib/src/base/uvm_globals.svh", 183)->__VnoInFunc_get_root(vlProcess, vlSymsp, __Vtask_get_root__6__Vfuncout);
        vlSymsp->TOP__uvm_pkg.uvm_report_info__Vstatic__top 
            = __Vtask_get_root__6__Vfuncout;
        VL_NULL_CHECK(vlSymsp->TOP__uvm_pkg.uvm_report_info__Vstatic__top, "../../uvm/distrib/src/base/uvm_globals.svh", 184)->__VnoInFunc_uvm_report_info(vlProcess, vlSymsp, vlSelfRef.__Vtask_uvm_report_info__4__id, vlSelfRef.__Vtask_uvm_report_info__4__message, __Vtask_uvm_report_info__4__verbosity, vlSelfRef.__Vtask_uvm_report_info__4__filename, __Vtask_uvm_report_info__4__line, vlSelfRef.__Vtask_uvm_report_info__4__context_name, (IData)(__Vtask_uvm_report_info__4__report_enabled_checked));
    }
    vlProcess->disableFork();
    VL_FINISH_MT("hello_uvm.sv", 8, "");
    vlProcess->state(VlProcess::FINISHED);
}

VL_ATTR_COLD void Vhello_uvm___024root___eval_final(Vhello_uvm___024root* vlSelf) {
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vhello_uvm___024root___eval_final\n"); );
    Vhello_uvm__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    auto& vlSelfRef = std::ref(*vlSelf).get();
}

VL_ATTR_COLD void Vhello_uvm___024root___eval_settle(Vhello_uvm___024root* vlSelf) {
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vhello_uvm___024root___eval_settle\n"); );
    Vhello_uvm__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    auto& vlSelfRef = std::ref(*vlSelf).get();
}

bool Vhello_uvm___024root___trigger_anySet__act(const VlUnpacked<QData/*63:0*/, 1> &in);

#ifdef VL_DEBUG
VL_ATTR_COLD void Vhello_uvm___024root___dump_triggers__act(const VlUnpacked<QData/*63:0*/, 1> &triggers, const std::string &tag) {
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vhello_uvm___024root___dump_triggers__act\n"); );
    // Body
    if ((1U & (~ (IData)(Vhello_uvm___024root___trigger_anySet__act(triggers))))) {
        VL_DBG_MSGS("         No '" + tag + "' region triggers active\n");
    }
    if ((1U & (IData)(triggers[0U]))) {
        VL_DBG_MSGS("         '" + tag + "' region trigger index 0 is active: @([true] __VdynSched.evaluate())\n");
    }
    if ((1U & (IData)((triggers[0U] >> 1U)))) {
        VL_DBG_MSGS("         '" + tag + "' region trigger index 1 is active: @([true] __VdlySched.awaitingCurrentTime())\n");
    }
    if ((1U & (IData)((triggers[0U] >> 2U)))) {
        VL_DBG_MSGS("         '" + tag + "' region trigger index 2 is active: @( (32'sh0 != uvm_pkg::uvm_objection__Vclpkg.m_scheduled_list.size()))\n");
    }
}
#endif  // VL_DEBUG

VL_ATTR_COLD void Vhello_uvm___024root___ctor_var_reset(Vhello_uvm___024root* vlSelf) {
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vhello_uvm___024root___ctor_var_reset\n"); );
    Vhello_uvm__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    auto& vlSelfRef = std::ref(*vlSelf).get();
    // Body
    vlSelf->__VnbaEventTrigger = 0;
    for (int __Vi0 = 0; __Vi0 < 1; ++__Vi0) {
        vlSelf->__VactTriggered[__Vi0] = 0;
    }
    for (int __Vi0 = 0; __Vi0 < 1; ++__Vi0) {
        vlSelf->__VactTriggeredAcc[__Vi0] = 0;
    }
    vlSelf->__Vtrigprevexpr_hcb469948__1 = 0;
    for (int __Vi0 = 0; __Vi0 < 1; ++__Vi0) {
        vlSelf->__VnbaTriggered[__Vi0] = 0;
    }
    vlSelf->__Vi = 0;
}
