// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Design internal header
// See VUVM_regblock.h for the primary calling header

#ifndef VERILATED_VUVM_REGBLOCK_UVM_PKG__03A__03AUVM_PHASE__VCLPKG_H_
#define VERILATED_VUVM_REGBLOCK_UVM_PKG__03A__03AUVM_PHASE__VCLPKG_H_  // guard

#include "verilated.h"
#include "verilated_covergroup.h"
#include "verilated_timing.h"
#include "verilated_random.h"
class VUVM_regblock_std__03a__03amailbox__Tz15;
class VUVM_regblock_std__03a__03aprocess;
class VUVM_regblock_uvm_pkg__03a__03a__VDynScope_9;
class VUVM_regblock_uvm_pkg__03a__03auvm_callback_iter__Tz15_TBz16;
class VUVM_regblock_uvm_pkg__03a__03auvm_cmdline_processor;
class VUVM_regblock_uvm_pkg__03a__03auvm_component;
class VUVM_regblock_uvm_pkg__03a__03auvm_coreservice_t;
class VUVM_regblock_uvm_pkg__03a__03auvm_domain;
class VUVM_regblock_uvm_pkg__03a__03auvm_object;
class VUVM_regblock_uvm_pkg__03a__03auvm_objection;
class VUVM_regblock_uvm_pkg__03a__03auvm_phase;
class VUVM_regblock_uvm_pkg__03a__03auvm_phase_cb;
class VUVM_regblock_uvm_pkg__03a__03auvm_phase_state_change;
class VUVM_regblock_uvm_pkg__03a__03auvm_root;
class VUVM_regblock_uvm_pkg__03a__03auvm_task_phase;
class VUVM_regblock_uvm_pkg__03a__03auvm_test_done_objection;


class VUVM_regblock__Syms;

class alignas(VL_CACHE_LINE_BYTES) VUVM_regblock_uvm_pkg__03a__03auvm_phase__Vclpkg final {
  public:

    // DESIGN SPECIFIC STATE
    CData/*0:0*/ __PVT__m_register_cb_uvm_phase_cb;
    CData/*0:0*/ __PVT__m_phase_trace;
    CData/*0:0*/ __PVT__m_use_ovm_run_semantic;
    IData/*31:0*/ __PVT__m_print_successors__Vstatic__level;
    VlAssocArray<VlClassRef<VUVM_regblock_uvm_pkg__03a__03auvm_phase>, CData/*0:0*/> __PVT__m_executing_phases;
    std::string __PVT__m_print_successors__Vstatic__spaces;
    std::string __Vfunc_uvm_report_enabled__2__id;
    std::string __Vtask_uvm_report_warning__6__id;
    std::string __Vtask_uvm_report_warning__6__message;
    std::string __Vtask_uvm_report_warning__6__filename;
    std::string __Vtask_uvm_report_warning__6__context_name;
    VlClassRef<VUVM_regblock_std__03a__03amailbox__Tz15> __PVT__m_phase_hopper;

    // INTERNAL VARIABLES
    VUVM_regblock__Syms* vlSymsp;
    const char* vlNamep;

    // CONSTRUCTORS
    VUVM_regblock_uvm_pkg__03a__03auvm_phase__Vclpkg();
    ~VUVM_regblock_uvm_pkg__03a__03auvm_phase__Vclpkg();
    void ctor(VUVM_regblock__Syms* symsp, const char* namep);
    void dtor();
    VL_UNCOPYABLE(VUVM_regblock_uvm_pkg__03a__03auvm_phase__Vclpkg);

    // INTERNAL METHODS
    void __Vconfigure(bool first);
    void __VnoInFunc_jump_all(VUVM_regblock__Syms* __restrict vlSymsp, VlClassRef<VUVM_regblock_uvm_pkg__03a__03auvm_phase> phase);
    VlCoroutine __VnoInFunc_m_run_phases(VlProcessRef vlProcess, VUVM_regblock__Syms* __restrict vlSymsp);
  private:
    VlCoroutine __VnoInFunc_m_run_phases____Vfork_1__0(VlProcessRef vlProcess, VlClassRef<VUVM_regblock_uvm_pkg__03a__03auvm_phase> unnamedblk153__DOT__phase);
};

#include "VUVM_regblock_uvm_pkg__03a__03auvm_object__Vclpkg.h"

class VUVM_regblock__Syms;

class VUVM_regblock_uvm_pkg__03a__03auvm_phase : public VUVM_regblock_uvm_pkg__03a__03auvm_object {
  public:

    // DESIGN SPECIFIC STATE
    CData/*0:0*/ __PVT__m_jump_bkwd;
    CData/*0:0*/ __PVT__m_jump_fwd;
    CData/*0:0*/ __PVT__m_premature_end;
    IData/*31:0*/ __PVT__max_ready_to_end_iter;
    IData/*31:0*/ __PVT__m_phase_type;
    IData/*31:0*/ __PVT__m_state;
    IData/*31:0*/ __PVT__m_run_count;
    IData/*31:0*/ __PVT__m_num_procs_not_yet_returned;
    IData/*31:0*/ __PVT__m_ready_to_end_count;
    VlAssocArray<VlClassRef<VUVM_regblock_uvm_pkg__03a__03auvm_phase>, CData/*0:0*/> __PVT__m_predecessors;
    VlAssocArray<VlClassRef<VUVM_regblock_uvm_pkg__03a__03auvm_phase>, CData/*0:0*/> __PVT__m_successors;
    std::string __Vfunc_uvm_report_enabled__11__id;
    std::string __Vtask_uvm_report_fatal__15__id;
    std::string __Vtask_uvm_report_fatal__15__message;
    std::string __Vtask_uvm_report_fatal__15__filename;
    std::string __Vtask_uvm_report_fatal__15__context_name;
    std::string __Vfunc_uvm_report_enabled__22__id;
    std::string __Vtask_uvm_report_fatal__27__id;
    std::string __Vtask_uvm_report_fatal__27__message;
    std::string __Vtask_uvm_report_fatal__27__filename;
    std::string __Vtask_uvm_report_fatal__27__context_name;
    std::string __Vfunc_uvm_report_enabled__34__id;
    std::string __Vtask_uvm_report_fatal__39__id;
    std::string __Vtask_uvm_report_fatal__39__message;
    std::string __Vtask_uvm_report_fatal__39__filename;
    std::string __Vtask_uvm_report_fatal__39__context_name;
    std::string __Vfunc_uvm_report_enabled__46__id;
    std::string __Vtask_uvm_report_fatal__51__id;
    std::string __Vtask_uvm_report_fatal__51__message;
    std::string __Vtask_uvm_report_fatal__51__filename;
    std::string __Vtask_uvm_report_fatal__51__context_name;
    std::string __Vfunc_uvm_report_enabled__55__id;
    std::string __Vtask_uvm_report_fatal__59__id;
    std::string __Vtask_uvm_report_fatal__59__message;
    std::string __Vtask_uvm_report_fatal__59__filename;
    std::string __Vtask_uvm_report_fatal__59__context_name;
    std::string __Vfunc_uvm_report_enabled__63__id;
    std::string __Vtask_uvm_report_fatal__67__id;
    std::string __Vtask_uvm_report_fatal__67__message;
    std::string __Vtask_uvm_report_fatal__67__filename;
    std::string __Vtask_uvm_report_fatal__67__context_name;
    std::string __Vfunc_uvm_report_enabled__79__id;
    std::string __Vtask_uvm_report_info__93__id;
    std::string __Vtask_uvm_report_info__93__message;
    std::string __Vtask_uvm_report_info__93__filename;
    std::string __Vtask_uvm_report_info__93__context_name;
    std::string __Vfunc_uvm_report_enabled__98__id;
    std::string __Vtask_uvm_report_fatal__104__id;
    std::string __Vtask_uvm_report_fatal__104__message;
    std::string __Vtask_uvm_report_fatal__104__filename;
    std::string __Vtask_uvm_report_fatal__104__context_name;
    std::string __Vfunc_uvm_report_enabled__115__id;
    std::string __Vtask_uvm_report_fatal__119__id;
    std::string __Vtask_uvm_report_fatal__119__message;
    std::string __Vtask_uvm_report_fatal__119__filename;
    std::string __Vtask_uvm_report_fatal__119__context_name;
    std::string __Vfunc_uvm_report_enabled__133__id;
    std::string __Vtask_uvm_report_info__139__id;
    std::string __Vtask_uvm_report_info__139__message;
    std::string __Vtask_uvm_report_info__139__filename;
    std::string __Vtask_uvm_report_info__139__context_name;
    std::string __Vfunc_uvm_report_enabled__184__id;
    std::string __Vtask_uvm_report_info__190__id;
    std::string __Vtask_uvm_report_info__190__message;
    std::string __Vtask_uvm_report_info__190__filename;
    std::string __Vtask_uvm_report_info__190__context_name;
    std::string __Vfunc_uvm_report_enabled__215__id;
    std::string __Vtask_uvm_report_info__221__id;
    std::string __Vtask_uvm_report_info__221__message;
    std::string __Vtask_uvm_report_info__221__filename;
    std::string __Vtask_uvm_report_info__221__context_name;
    std::string __Vtask___VforkTask_1__225____VlefCall_13__get_full_name;
    std::string __Vtask___VforkTask_1__225____VlefCall_10__get_full_name;
    std::string __Vtask___VforkTask_1__225____VlefCall_7__get_full_name;
    std::string __Vtask___VforkTask_1__225____VlefCall_4__get_full_name;
    std::string __Vtask___VforkTask_1__225____VlefCall_1__get_name;
    std::string __Vtask_get_name__227__Vfuncout;
    std::string __Vfunc_uvm_report_enabled__229__id;
    std::string __Vfunc_get_full_name__233__Vfuncout;
    std::string __Vtask_uvm_report_info__235__id;
    std::string __Vtask_uvm_report_info__235__message;
    std::string __Vtask_uvm_report_info__235__filename;
    std::string __Vtask_uvm_report_info__235__context_name;
    std::string __Vfunc_uvm_report_enabled__239__id;
    std::string __Vfunc_get_full_name__243__Vfuncout;
    std::string __Vtask_uvm_report_info__245__id;
    std::string __Vtask_uvm_report_info__245__message;
    std::string __Vtask_uvm_report_info__245__filename;
    std::string __Vtask_uvm_report_info__245__context_name;
    std::string __Vfunc_uvm_report_enabled__251__id;
    std::string __Vfunc_get_full_name__255__Vfuncout;
    std::string __Vtask_uvm_report_info__257__id;
    std::string __Vtask_uvm_report_info__257__message;
    std::string __Vtask_uvm_report_info__257__filename;
    std::string __Vtask_uvm_report_info__257__context_name;
    std::string __Vfunc_uvm_report_enabled__261__id;
    std::string __Vfunc_get_full_name__265__Vfuncout;
    std::string __Vtask_uvm_report_info__267__id;
    std::string __Vtask_uvm_report_info__267__message;
    std::string __Vtask_uvm_report_info__267__filename;
    std::string __Vtask_uvm_report_info__267__context_name;
    std::string __Vtask___VforkTask_2__278____VlefCall_27__get_full_name;
    std::string __Vtask___VforkTask_2__278____VlefCall_24__convert2string;
    std::string __Vtask___VforkTask_2__278____VlefCall_23__get_full_name;
    std::string __Vtask___VforkTask_2__278____VlefCall_21__get_full_name;
    std::string __Vtask___VforkTask_2__278____VlefCall_16__get_full_name;
    std::string __Vtask___VforkTask_2__278____VlefCall_13__convert2string;
    std::string __Vtask___VforkTask_2__278____VlefCall_12__get_full_name;
    std::string __Vtask___VforkTask_2__278____VlefCall_10__get_full_name;
    std::string __Vtask___VforkTask_2__278____VlefCall_5__get_full_name;
    std::string __Vtask___VforkTask_2__278____VlefCall_2__get_full_name;
    std::string __Vtask___VforkTask_2__278____VlefCall_0__get_name;
    std::string __Vfunc_get_name__279__Vfuncout;
    std::string __Vfunc_uvm_report_enabled__280__id;
    std::string __Vfunc_get_full_name__284__Vfuncout;
    std::string __Vtask_uvm_report_info__286__id;
    std::string __Vtask_uvm_report_info__286__message;
    std::string __Vtask_uvm_report_info__286__filename;
    std::string __Vtask_uvm_report_info__286__context_name;
    std::string __Vfunc_uvm_report_enabled__290__id;
    std::string __Vfunc_get_full_name__294__Vfuncout;
    std::string __Vtask_uvm_report_info__296__id;
    std::string __Vtask_uvm_report_info__296__message;
    std::string __Vtask_uvm_report_info__296__filename;
    std::string __Vtask_uvm_report_info__296__context_name;
    std::string __Vfunc_uvm_report_enabled__301__id;
    std::string __Vfunc_get_full_name__305__Vfuncout;
    std::string __Vtask_get_full_name__307__Vfuncout;
    std::string __Vtask_convert2string__308__Vfuncout;
    std::string __Vtask_uvm_report_info__309__id;
    std::string __Vtask_uvm_report_info__309__message;
    std::string __Vtask_uvm_report_info__309__filename;
    std::string __Vtask_uvm_report_info__309__context_name;
    std::string __Vfunc_uvm_report_enabled__313__id;
    std::string __Vtask_uvm_report_fatal__317__id;
    std::string __Vtask_uvm_report_fatal__317__message;
    std::string __Vtask_uvm_report_fatal__317__filename;
    std::string __Vtask_uvm_report_fatal__317__context_name;
    std::string __Vfunc_uvm_report_enabled__321__id;
    std::string __Vfunc_get_full_name__325__Vfuncout;
    std::string __Vtask_uvm_report_info__327__id;
    std::string __Vtask_uvm_report_info__327__message;
    std::string __Vtask_uvm_report_info__327__filename;
    std::string __Vtask_uvm_report_info__327__context_name;
    std::string __Vfunc_uvm_report_enabled__332__id;
    std::string __Vfunc_get_full_name__336__Vfuncout;
    std::string __Vtask_get_full_name__338__Vfuncout;
    std::string __Vtask_convert2string__339__Vfuncout;
    std::string __Vtask_uvm_report_info__340__id;
    std::string __Vtask_uvm_report_info__340__message;
    std::string __Vtask_uvm_report_info__340__filename;
    std::string __Vtask_uvm_report_info__340__context_name;
    std::string __Vfunc_uvm_report_enabled__344__id;
    std::string __Vtask_uvm_report_fatal__348__id;
    std::string __Vtask_uvm_report_fatal__348__message;
    std::string __Vtask_uvm_report_fatal__348__filename;
    std::string __Vtask_uvm_report_fatal__348__context_name;
    std::string __Vfunc_uvm_report_enabled__352__id;
    std::string __Vfunc_get_full_name__356__Vfuncout;
    std::string __Vtask_uvm_report_info__358__id;
    std::string __Vtask_uvm_report_info__358__message;
    std::string __Vtask_uvm_report_info__358__filename;
    std::string __Vtask_uvm_report_info__358__context_name;
    std::string __Vfunc_uvm_report_enabled__367__id;
    std::string __Vtask_uvm_report_info__375__id;
    std::string __Vtask_uvm_report_info__375__message;
    std::string __Vtask_uvm_report_info__375__filename;
    std::string __Vtask_uvm_report_info__375__context_name;
    std::string __Vfunc_uvm_report_enabled__379__id;
    std::string __Vtask_uvm_report_info__386__id;
    std::string __Vtask_uvm_report_info__386__message;
    std::string __Vtask_uvm_report_info__386__filename;
    std::string __Vtask_uvm_report_info__386__context_name;
    std::string __Vfunc_uvm_report_enabled__390__id;
    std::string __Vtask_uvm_report_info__396__id;
    std::string __Vtask_uvm_report_info__396__message;
    std::string __Vtask_uvm_report_info__396__filename;
    std::string __Vtask_uvm_report_info__396__context_name;
    std::string __Vfunc_uvm_report_enabled__401__id;
    std::string __Vtask_uvm_report_info__407__id;
    std::string __Vtask_uvm_report_info__407__message;
    std::string __Vtask_uvm_report_info__407__filename;
    std::string __Vtask_uvm_report_info__407__context_name;
    std::string __Vfunc_uvm_report_enabled__424__id;
    std::string __Vtask_uvm_report_info__430__id;
    std::string __Vtask_uvm_report_info__430__message;
    std::string __Vtask_uvm_report_info__430__filename;
    std::string __Vtask_uvm_report_info__430__context_name;
    std::string __Vfunc_uvm_report_enabled__445__id;
    std::string __Vtask_uvm_report_info__452__id;
    std::string __Vtask_uvm_report_info__452__message;
    std::string __Vtask_uvm_report_info__452__filename;
    std::string __Vtask_uvm_report_info__452__context_name;
    std::string __Vfunc_uvm_report_enabled__463__id;
    std::string __Vtask_uvm_report_info__469__id;
    std::string __Vtask_uvm_report_info__469__message;
    std::string __Vtask_uvm_report_info__469__filename;
    std::string __Vtask_uvm_report_info__469__context_name;
    std::string __Vfunc_uvm_report_enabled__476__id;
    std::string __Vtask_uvm_report_info__482__id;
    std::string __Vtask_uvm_report_info__482__message;
    std::string __Vtask_uvm_report_info__482__filename;
    std::string __Vtask_uvm_report_info__482__context_name;
    std::string __Vfunc_uvm_report_enabled__487__id;
    std::string __Vtask_uvm_report_info__493__id;
    std::string __Vtask_uvm_report_info__493__message;
    std::string __Vtask_uvm_report_info__493__filename;
    std::string __Vtask_uvm_report_info__493__context_name;
    std::string __Vfunc_uvm_report_enabled__497__id;
    std::string __Vtask_uvm_report_info__503__id;
    std::string __Vtask_uvm_report_info__503__message;
    std::string __Vtask_uvm_report_info__503__filename;
    std::string __Vtask_uvm_report_info__503__context_name;
    std::string __Vfunc_uvm_report_enabled__509__id;
    std::string __Vtask_uvm_report_error__515__id;
    std::string __Vtask_uvm_report_error__515__message;
    std::string __Vtask_uvm_report_error__515__filename;
    std::string __Vtask_uvm_report_error__515__context_name;
    std::string __Vfunc_uvm_report_enabled__526__id;
    std::string __Vtask_uvm_report_fatal__530__id;
    std::string __Vtask_uvm_report_fatal__530__message;
    std::string __Vtask_uvm_report_fatal__530__filename;
    std::string __Vtask_uvm_report_fatal__530__context_name;
    std::string __Vfunc_uvm_report_enabled__535__id;
    std::string __Vtask_uvm_report_fatal__539__id;
    std::string __Vtask_uvm_report_fatal__539__message;
    std::string __Vtask_uvm_report_fatal__539__filename;
    std::string __Vtask_uvm_report_fatal__539__context_name;
    std::string __Vfunc_uvm_report_enabled__546__id;
    std::string __Vtask_uvm_report_fatal__550__id;
    std::string __Vtask_uvm_report_fatal__550__message;
    std::string __Vtask_uvm_report_fatal__550__filename;
    std::string __Vtask_uvm_report_fatal__550__context_name;
    std::string __Vfunc_uvm_report_enabled__554__id;
    std::string __Vtask_uvm_report_fatal__558__id;
    std::string __Vtask_uvm_report_fatal__558__message;
    std::string __Vtask_uvm_report_fatal__558__filename;
    std::string __Vtask_uvm_report_fatal__558__context_name;
    std::string __Vfunc_uvm_report_enabled__563__id;
    std::string __Vtask_uvm_report_fatal__567__id;
    std::string __Vtask_uvm_report_fatal__567__message;
    std::string __Vtask_uvm_report_fatal__567__filename;
    std::string __Vtask_uvm_report_fatal__567__context_name;
    std::string __Vfunc_uvm_report_enabled__572__id;
    std::string __Vtask_uvm_report_fatal__576__id;
    std::string __Vtask_uvm_report_fatal__576__message;
    std::string __Vtask_uvm_report_fatal__576__filename;
    std::string __Vtask_uvm_report_fatal__576__context_name;
    std::string __Vfunc_uvm_report_enabled__583__id;
    std::string __Vtask_uvm_report_fatal__587__id;
    std::string __Vtask_uvm_report_fatal__587__message;
    std::string __Vtask_uvm_report_fatal__587__filename;
    std::string __Vtask_uvm_report_fatal__587__context_name;
    std::string __Vfunc_uvm_report_enabled__591__id;
    std::string __Vtask_uvm_report_fatal__595__id;
    std::string __Vtask_uvm_report_fatal__595__message;
    std::string __Vtask_uvm_report_fatal__595__filename;
    std::string __Vtask_uvm_report_fatal__595__context_name;
    std::string __Vfunc_uvm_report_enabled__599__id;
    std::string __Vtask_uvm_report_error__604__id;
    std::string __Vtask_uvm_report_error__604__message;
    std::string __Vtask_uvm_report_error__604__filename;
    std::string __Vtask_uvm_report_error__604__context_name;
    std::string __Vfunc_uvm_report_enabled__612__id;
    std::string __Vtask_uvm_report_fatal__616__id;
    std::string __Vtask_uvm_report_fatal__616__message;
    std::string __Vtask_uvm_report_fatal__616__filename;
    std::string __Vtask_uvm_report_fatal__616__context_name;
    std::string __Vfunc_uvm_report_enabled__620__id;
    std::string __Vtask_uvm_report_info__625__id;
    std::string __Vtask_uvm_report_info__625__message;
    std::string __Vtask_uvm_report_info__625__filename;
    std::string __Vtask_uvm_report_info__625__context_name;
    std::string __Vfunc_uvm_report_enabled__629__id;
    std::string __Vtask_uvm_report_info__634__id;
    std::string __Vtask_uvm_report_info__634__message;
    std::string __Vtask_uvm_report_info__634__filename;
    std::string __Vtask_uvm_report_info__634__context_name;
    std::string __Vfunc_uvm_report_enabled__651__id;
    std::string __Vtask_uvm_report_info__656__id;
    std::string __Vtask_uvm_report_info__656__message;
    std::string __Vtask_uvm_report_info__656__filename;
    std::string __Vtask_uvm_report_info__656__context_name;
    std::string __Vfunc_uvm_report_enabled__666__id;
    std::string __Vtask_uvm_report_info__672__id;
    std::string __Vtask_uvm_report_info__672__message;
    std::string __Vtask_uvm_report_info__672__filename;
    std::string __Vtask_uvm_report_info__672__context_name;
    std::string __Vfunc_uvm_report_enabled__676__id;
    std::string __Vtask_uvm_report_info__681__id;
    std::string __Vtask_uvm_report_info__681__message;
    std::string __Vtask_uvm_report_info__681__filename;
    std::string __Vtask_uvm_report_info__681__context_name;
    VlClassRef<VUVM_regblock_uvm_pkg__03a__03auvm_phase> __PVT__m_parent;
    VlClassRef<VUVM_regblock_uvm_pkg__03a__03auvm_phase> __PVT__m_imp;
    VlClassRef<VUVM_regblock_std__03a__03aprocess> __PVT__m_phase_proc;
    VlClassRef<VUVM_regblock_uvm_pkg__03a__03auvm_phase> __PVT__m_end_node;
    VlQueue<VlClassRef<VUVM_regblock_uvm_pkg__03a__03auvm_phase>> __PVT__m_sync;
    VlClassRef<VUVM_regblock_uvm_pkg__03a__03auvm_objection> __PVT__phase_done;
    VlClassRef<VUVM_regblock_uvm_pkg__03a__03auvm_phase> __PVT__m_jump_phase;

    // INTERNAL METHODS
    virtual const char* typeName() const { return "uvm_pkg::uvm_phase"; }
    VlClass* clone() const { return new VUVM_regblock_uvm_pkg__03a__03auvm_phase(*this); }
    virtual void __VnoInFunc___VBasicRand(VUVM_regblock__Syms* __restrict vlSymsp, IData/*31:0*/ &__VBasicRand__Vfuncrtn);
    virtual void __VnoInFunc___Vsetup_constraints(VUVM_regblock__Syms* __restrict vlSymsp);
    void __VnoInFunc_add(VlProcessRef vlProcess, VUVM_regblock__Syms* __restrict vlSymsp, VlClassRef<VUVM_regblock_uvm_pkg__03a__03auvm_phase> phase, VlClassRef<VUVM_regblock_uvm_pkg__03a__03auvm_phase> with_phase, VlClassRef<VUVM_regblock_uvm_pkg__03a__03auvm_phase> after_phase, VlClassRef<VUVM_regblock_uvm_pkg__03a__03auvm_phase> before_phase);
    void __VnoInFunc_clear(VlProcessRef vlProcess, VUVM_regblock__Syms* __restrict vlSymsp, IData/*31:0*/ state);
    void __VnoInFunc_clear_successors(VlProcessRef vlProcess, VUVM_regblock__Syms* __restrict vlSymsp, IData/*31:0*/ state, VlClassRef<VUVM_regblock_uvm_pkg__03a__03auvm_phase> end_state);
    void __VnoInFunc_convert2string(VlProcessRef vlProcess, VUVM_regblock__Syms* __restrict vlSymsp, std::string &convert2string__Vfuncrtn);
    virtual void __VnoInFunc_drop_objection(VlProcessRef vlProcess, VUVM_regblock__Syms* __restrict vlSymsp, VlClassRef<VUVM_regblock_uvm_pkg__03a__03auvm_object> obj, std::string description, IData/*31:0*/ count);
    void __VnoInFunc_end_prematurely(VUVM_regblock__Syms* __restrict vlSymsp);
    virtual void __VnoInFunc_exec_func(VlProcessRef vlProcess, VUVM_regblock__Syms* __restrict vlSymsp, VlClassRef<VUVM_regblock_uvm_pkg__03a__03auvm_component> comp, VlClassRef<VUVM_regblock_uvm_pkg__03a__03auvm_phase> phase);
    virtual VlCoroutine __VnoInFunc_exec_task(VlProcessRef vlProcess, VUVM_regblock__Syms* __restrict vlSymsp, VlClassRef<VUVM_regblock_uvm_pkg__03a__03auvm_component> comp, VlClassRef<VUVM_regblock_uvm_pkg__03a__03auvm_phase> phase);
    virtual void __VnoInFunc_execute(VlProcessRef vlProcess, VUVM_regblock__Syms* __restrict vlSymsp, VlClassRef<VUVM_regblock_uvm_pkg__03a__03auvm_component> comp, VlClassRef<VUVM_regblock_uvm_pkg__03a__03auvm_phase> phase);
    VlCoroutine __VnoInFunc_execute_phase(VlProcessRef vlProcess, VUVM_regblock__Syms* __restrict vlSymsp);
  private:
    VlCoroutine __VnoInFunc_execute_phase____Vfork_1__0(VlProcessRef vlProcess, VUVM_regblock__Syms* __restrict vlSymsp, VlClassRef<VUVM_regblock_uvm_pkg__03a__03a__VDynScope_9> __VDynScope_execute_phase_0);
    VlCoroutine __VnoInFunc_execute_phase____Vfork_2__0(VlProcessRef vlProcess, VUVM_regblock__Syms* __restrict vlSymsp);
    VlCoroutine __VnoInFunc_execute_phase____Vfork_2__0____Vfork_3__0(VlProcessRef vlProcess, VUVM_regblock__Syms* __restrict vlSymsp, IData/*31:0*/ __Vintraval_h8b5250ea__0);
    VlCoroutine __VnoInFunc_execute_phase____Vfork_4__0(VlProcessRef vlProcess, VUVM_regblock__Syms* __restrict vlSymsp, VlForkSync __Vfork_4__sync, IData/*31:0*/ &__VlefCall_7__uvm_report_enabled, std::string &__VlefCall_8__get_full_name, IData/*31:0*/ &__VlefCall_9__get_inst_id, VlClassRef<VUVM_regblock_uvm_pkg__03a__03a__VDynScope_9> &__VDynScope_execute_phase_0);
    VlCoroutine __VnoInFunc_execute_phase____Vfork_4__0____Vfork_5__0(VlProcessRef vlProcess, VUVM_regblock__Syms* __restrict vlSymsp, VlForkSync __Vfork_5__sync, IData/*31:0*/ __VlefCall_7__uvm_report_enabled, std::string __VlefCall_8__get_full_name, IData/*31:0*/ __VlefCall_9__get_inst_id);
    VlCoroutine __VnoInFunc_execute_phase____Vfork_4__0____Vfork_5__1(VlProcessRef vlProcess, VUVM_regblock__Syms* __restrict vlSymsp, VlForkSync __Vfork_5__sync, VlClassRef<VUVM_regblock_uvm_pkg__03a__03a__VDynScope_9> __VDynScope_execute_phase_0);
    VlCoroutine __VnoInFunc_execute_phase____Vfork_4__0____Vfork_5__1____Vfork_6__0(VlProcessRef vlProcess, VUVM_regblock__Syms* __restrict vlSymsp);
    VlCoroutine __VnoInFunc_execute_phase____Vfork_4__0____Vfork_5__1____Vfork_6__0____Vfork_7__0(VlProcessRef vlProcess, VUVM_regblock__Syms* __restrict vlSymsp, IData/*31:0*/ __Vintraval_h8b5250ea__1);
    VlCoroutine __VnoInFunc_execute_phase____Vfork_4__0____Vfork_5__1____Vfork_8__0(VlProcessRef vlProcess, VUVM_regblock__Syms* __restrict vlSymsp);
    VlCoroutine __VnoInFunc_execute_phase____Vfork_4__0____Vfork_5__1____Vfork_8__0____Vfork_9__0(VlProcessRef vlProcess, VUVM_regblock__Syms* __restrict vlSymsp, IData/*31:0*/ __Vintraval_h8b5250ea__2);
    VlCoroutine __VnoInFunc_execute_phase____Vfork_4__0____Vfork_5__2(VlProcessRef vlProcess, VUVM_regblock__Syms* __restrict vlSymsp, VlForkSync __Vfork_5__sync, VlClassRef<VUVM_regblock_uvm_pkg__03a__03a__VDynScope_9> __VDynScope_execute_phase_0);
  public:
    void __VnoInFunc_find(VlProcessRef vlProcess, VUVM_regblock__Syms* __restrict vlSymsp, VlClassRef<VUVM_regblock_uvm_pkg__03a__03auvm_phase> phase, CData/*0:0*/ stay_in_scope, VlClassRef<VUVM_regblock_uvm_pkg__03a__03auvm_phase> &find__Vfuncrtn);
    void __VnoInFunc_find_by_name(VUVM_regblock__Syms* __restrict vlSymsp, std::string name, CData/*0:0*/ stay_in_scope, VlClassRef<VUVM_regblock_uvm_pkg__03a__03auvm_phase> &find_by_name__Vfuncrtn);
    void __VnoInFunc_get_adjacent_predecessor_nodes(VUVM_regblock__Syms* __restrict vlSymsp, VlQueue<VlClassRef<VUVM_regblock_uvm_pkg__03a__03auvm_phase>> &pred);
    void __VnoInFunc_get_adjacent_successor_nodes(VUVM_regblock__Syms* __restrict vlSymsp, VlQueue<VlClassRef<VUVM_regblock_uvm_pkg__03a__03auvm_phase>> &succ);
    void __VnoInFunc_get_begin_node(VUVM_regblock__Syms* __restrict vlSymsp, VlClassRef<VUVM_regblock_uvm_pkg__03a__03auvm_phase> &get_begin_node__Vfuncrtn);
    void __VnoInFunc_get_domain(VlProcessRef vlProcess, VUVM_regblock__Syms* __restrict vlSymsp, VlClassRef<VUVM_regblock_uvm_pkg__03a__03auvm_domain> &get_domain__Vfuncrtn);
    void __VnoInFunc_get_domain_name(VlProcessRef vlProcess, VUVM_regblock__Syms* __restrict vlSymsp, std::string &get_domain_name__Vfuncrtn);
    void __VnoInFunc_get_end_node(VUVM_regblock__Syms* __restrict vlSymsp, VlClassRef<VUVM_regblock_uvm_pkg__03a__03auvm_phase> &get_end_node__Vfuncrtn);
    virtual void __VnoInFunc_get_full_name(VlProcessRef vlProcess, VUVM_regblock__Syms* __restrict vlSymsp, std::string &get_full_name__Vfuncrtn);
    void __VnoInFunc_get_imp(VUVM_regblock__Syms* __restrict vlSymsp, VlClassRef<VUVM_regblock_uvm_pkg__03a__03auvm_phase> &get_imp__Vfuncrtn);
    void __VnoInFunc_get_jump_target(VUVM_regblock__Syms* __restrict vlSymsp, VlClassRef<VUVM_regblock_uvm_pkg__03a__03auvm_phase> &get_jump_target__Vfuncrtn);
    void __VnoInFunc_get_objection(VUVM_regblock__Syms* __restrict vlSymsp, VlClassRef<VUVM_regblock_uvm_pkg__03a__03auvm_objection> &get_objection__Vfuncrtn);
    virtual void __VnoInFunc_get_objection_count(VUVM_regblock__Syms* __restrict vlSymsp, VlClassRef<VUVM_regblock_uvm_pkg__03a__03auvm_object> obj, IData/*31:0*/ &get_objection_count__Vfuncrtn);
    void __VnoInFunc_get_parent(VUVM_regblock__Syms* __restrict vlSymsp, VlClassRef<VUVM_regblock_uvm_pkg__03a__03auvm_phase> &get_parent__Vfuncrtn);
    void __VnoInFunc_get_phase_type(VUVM_regblock__Syms* __restrict vlSymsp, IData/*31:0*/ &get_phase_type__Vfuncrtn);
    void __VnoInFunc_get_predecessors_for_successors(VUVM_regblock__Syms* __restrict vlSymsp, VlAssocArray<VlClassRef<VUVM_regblock_uvm_pkg__03a__03auvm_phase>, CData/*0:0*/> &pred_of_succ);
    void __VnoInFunc_get_ready_to_end_count(VUVM_regblock__Syms* __restrict vlSymsp, IData/*31:0*/ &get_ready_to_end_count__Vfuncrtn);
    void __VnoInFunc_get_run_count(VUVM_regblock__Syms* __restrict vlSymsp, IData/*31:0*/ &get_run_count__Vfuncrtn);
    void __VnoInFunc_get_schedule(VUVM_regblock__Syms* __restrict vlSymsp, CData/*0:0*/ hier, VlClassRef<VUVM_regblock_uvm_pkg__03a__03auvm_phase> &get_schedule__Vfuncrtn);
    void __VnoInFunc_get_schedule_name(VUVM_regblock__Syms* __restrict vlSymsp, CData/*0:0*/ hier, std::string &get_schedule_name__Vfuncrtn);
    void __VnoInFunc_get_state(VUVM_regblock__Syms* __restrict vlSymsp, IData/*31:0*/ &get_state__Vfuncrtn);
    void __VnoInFunc_is(VUVM_regblock__Syms* __restrict vlSymsp, VlClassRef<VUVM_regblock_uvm_pkg__03a__03auvm_phase> phase, CData/*0:0*/ &is__Vfuncrtn);
    void __VnoInFunc_is_after(VUVM_regblock__Syms* __restrict vlSymsp, VlClassRef<VUVM_regblock_uvm_pkg__03a__03auvm_phase> phase, CData/*0:0*/ &is_after__Vfuncrtn);
    void __VnoInFunc_is_before(VlProcessRef vlProcess, VUVM_regblock__Syms* __restrict vlSymsp, VlClassRef<VUVM_regblock_uvm_pkg__03a__03auvm_phase> phase, CData/*0:0*/ &is_before__Vfuncrtn);
    void __VnoInFunc_is_domain(VUVM_regblock__Syms* __restrict vlSymsp, CData/*0:0*/ &is_domain__Vfuncrtn);
    void __VnoInFunc_jump(VUVM_regblock__Syms* __restrict vlSymsp, VlClassRef<VUVM_regblock_uvm_pkg__03a__03auvm_phase> phase);
    void __VnoInFunc_kill(VUVM_regblock__Syms* __restrict vlSymsp);
    void __VnoInFunc_kill_successors(VUVM_regblock__Syms* __restrict vlSymsp);
    void __VnoInFunc_m_aa2string(VUVM_regblock__Syms* __restrict vlSymsp, VlAssocArray<VlClassRef<VUVM_regblock_uvm_pkg__03a__03auvm_phase>, CData/*0:0*/> aa, std::string &m_aa2string__Vfuncrtn);
    void __VnoInFunc_m_find_predecessor(VlProcessRef vlProcess, VUVM_regblock__Syms* __restrict vlSymsp, VlClassRef<VUVM_regblock_uvm_pkg__03a__03auvm_phase> phase, CData/*0:0*/ stay_in_scope, VlClassRef<VUVM_regblock_uvm_pkg__03a__03auvm_phase> orig_phase, VlClassRef<VUVM_regblock_uvm_pkg__03a__03auvm_phase> &m_find_predecessor__Vfuncrtn);
    void __VnoInFunc_m_find_predecessor_by_name(VUVM_regblock__Syms* __restrict vlSymsp, std::string name, CData/*0:0*/ stay_in_scope, VlClassRef<VUVM_regblock_uvm_pkg__03a__03auvm_phase> orig_phase, VlClassRef<VUVM_regblock_uvm_pkg__03a__03auvm_phase> &m_find_predecessor_by_name__Vfuncrtn);
    void __VnoInFunc_m_find_successor(VlProcessRef vlProcess, VUVM_regblock__Syms* __restrict vlSymsp, VlClassRef<VUVM_regblock_uvm_pkg__03a__03auvm_phase> phase, CData/*0:0*/ stay_in_scope, VlClassRef<VUVM_regblock_uvm_pkg__03a__03auvm_phase> orig_phase, VlClassRef<VUVM_regblock_uvm_pkg__03a__03auvm_phase> &m_find_successor__Vfuncrtn);
    void __VnoInFunc_m_find_successor_by_name(VUVM_regblock__Syms* __restrict vlSymsp, std::string name, CData/*0:0*/ stay_in_scope, VlClassRef<VUVM_regblock_uvm_pkg__03a__03auvm_phase> orig_phase, VlClassRef<VUVM_regblock_uvm_pkg__03a__03auvm_phase> &m_find_successor_by_name__Vfuncrtn);
    virtual void __VnoInFunc_m_get_transitive_children(VUVM_regblock__Syms* __restrict vlSymsp, VlQueue<VlClassRef<VUVM_regblock_uvm_pkg__03a__03auvm_phase>> &phases);
    void __VnoInFunc_m_print_successors(VUVM_regblock__Syms* __restrict vlSymsp);
    void __VnoInFunc_m_print_termination_state(VUVM_regblock__Syms* __restrict vlSymsp);
    void __VnoInFunc_m_report_null_objection(VlProcessRef vlProcess, VUVM_regblock__Syms* __restrict vlSymsp, VlClassRef<VUVM_regblock_uvm_pkg__03a__03auvm_object> obj, std::string description, IData/*31:0*/ count, std::string action);
    void __VnoInFunc_m_terminate_phase(VUVM_regblock__Syms* __restrict vlSymsp);
    VlCoroutine __VnoInFunc_m_wait_for_pred(VlProcessRef vlProcess, VUVM_regblock__Syms* __restrict vlSymsp);
    virtual void __VnoInFunc_raise_objection(VlProcessRef vlProcess, VUVM_regblock__Syms* __restrict vlSymsp, VlClassRef<VUVM_regblock_uvm_pkg__03a__03auvm_object> obj, std::string description, IData/*31:0*/ count);
    virtual void __VnoInFunc_randomize(VUVM_regblock__Syms* __restrict vlSymsp, IData/*31:0*/ &randomize__Vfuncrtn);
    void __VnoInFunc_set_jump_phase(VUVM_regblock__Syms* __restrict vlSymsp, VlClassRef<VUVM_regblock_uvm_pkg__03a__03auvm_phase> phase);
    void __VnoInFunc_sync(VUVM_regblock__Syms* __restrict vlSymsp, VlClassRef<VUVM_regblock_uvm_pkg__03a__03auvm_domain> target, VlClassRef<VUVM_regblock_uvm_pkg__03a__03auvm_phase> phase, VlClassRef<VUVM_regblock_uvm_pkg__03a__03auvm_phase> with_phase);
    virtual void __VnoInFunc_traverse(VlProcessRef vlProcess, VUVM_regblock__Syms* __restrict vlSymsp, VlClassRef<VUVM_regblock_uvm_pkg__03a__03auvm_component> comp, VlClassRef<VUVM_regblock_uvm_pkg__03a__03auvm_phase> phase, IData/*31:0*/ state);
    void __VnoInFunc_unsync(VUVM_regblock__Syms* __restrict vlSymsp, VlClassRef<VUVM_regblock_uvm_pkg__03a__03auvm_domain> target, VlClassRef<VUVM_regblock_uvm_pkg__03a__03auvm_phase> phase, VlClassRef<VUVM_regblock_uvm_pkg__03a__03auvm_phase> with_phase);
    VlCoroutine __VnoInFunc_wait_for_self_and_siblings_to_drop(VlProcessRef vlProcess, VUVM_regblock__Syms* __restrict vlSymsp);
    VlCoroutine __VnoInFunc_wait_for_state(VlProcessRef vlProcess, VUVM_regblock__Syms* __restrict vlSymsp, IData/*31:0*/ state, IData/*31:0*/ op);
  private:
    void _ctor_var_reset(VUVM_regblock__Syms* __restrict vlSymsp);
  public:
    VUVM_regblock_uvm_pkg__03a__03auvm_phase() = default;
    void init(VlProcessRef vlProcess, VUVM_regblock__Syms* __restrict vlSymsp, std::string name, IData/*31:0*/ phase_type, VlClassRef<VUVM_regblock_uvm_pkg__03a__03auvm_phase> parent);
    virtual ~VUVM_regblock_uvm_pkg__03a__03auvm_phase();
};


#endif  // guard
